### ISSUE TITLE
Instalaciones Generales

### ISSUE THREAD

**Issue by jalliende** [IIC2143-2020-1/proyecto#1]
Hola, revise la wiki y aparecen algunos link para instalar los programas. Pero mi duda es si es que podrían especificar más que versión y poner los links que me dirijan de manera exacta a esa versión. ya que por ejemplo el link de ruby me lleva a un lugar donde existen 4 versiones, y el de Ruby and Rails me lleva a la versión 6.0.2.1 siendo que nos dicen que instalemos la 5.2 y dentro de esa pagina no pude encontrar la versión solicitada. 
Muchas gracias.

**Comment by elramirezv** [comment]
Hola!

En el enunciado del proyecto habrá más detalle en esto, pero para resolver tu duda, este semestre utilizaremos **Ruby 2.6.x** y **Rails 5.2** (tal como dice la Wiki). Te recomiendo seguir la guía de instalación de [Go Rails](https://gorails.com/setup/ubuntu/19.10) , puedes elegir la versión que quieras instalar, es bastante clara y está para Windows/Ubuntu/macOs.

**Comment by Juanvg213** [comment]
¿Se puede usar una versión más antigua de Ruby? (versión 2.6x)

**Comment by elramirezv** [comment]
Hola @Juanvg213 !

De que se puede, se puede. Pero **no** lo recomendamos por 2 razones: 
1. En los proyectos de Rails, existe un archivo llamado `.ruby-version`, en el cual debes especificar la versión de Ruby que estás utilizando, si es que es incongruente con la que tienes instalada, el servidor no va a correr. Por lo tanto, tendrías que cambiarlo manualmente **cada vez** que trabajes en el proyecto (si es que tus compañeros tienen la versión **2.7**).
2. Al igual que en Python, podría haber cosas que no funcionen correctamente por la diferencia entre versiones.

**Comment by tomasalvarez13** [comment]
Hola, que me recomiendan hacer si esque tengo la version 2.6.x de ruby, y la 6.0.2.1 de rails? Gracias

**Comment by elramirezv** [comment]
Hola @tomasalvarez13!

Te recomendamos instalar las versiones mencionadas anteriormente, o sino, no podrás correr correctamente tu proyecto :(. Lo bueno, es que puedes tener más de una versión instalada en tu computador y cambiar dependiendo del proyecto 👍 

Puedes seguir la guía de [Go Rails](https://gorails.com/setup/ubuntu/19.10) para instalar las versiones. Y en el siguiente [link](https://developpaper.com/using-rvm-to-control-switching-ruby-rails-version/) puedes ver cómo elegir entre las versiones que tengas instaladas.

Cabe mencionar que, si uno de tus compañeros hace el setup inicial del proyecto con las versiones "correctas", entonces cuando intentes correr el servidor, Ruby por si solo va a "ir a buscar" esas versiones. Por lo tanto, solo bastaría tenerlas instaladas y no tendrías que hacer un "switch" manual entre versiones.

**Comment by tomasalvarez13** [comment]
Gracias, pero al instalar rails, me arroja el siguiente error:
 ```
The last version of nokogiri (>= 1.6) to support your Ruby & RubyGems was 1.10.9. Try installing it with `gem install nokogiri -v 1.10.9` and then running the current command again
        nokogiri requires Ruby version >= 2.3, < 2.7.dev. The current ruby version is 2.7.0.0.
```

Por lo que entiendo, aunque intente instalar nokogiri, no me dejara ya que la versión de ruby debe ser < 2.7

**Comment by elramirezv** [comment]
Eso te lo tira cuando corres: `gem install rails -v 6.0.2.1` ?

**Comment by tomasalvarez13** [comment]
O cuando corro: `gem install rails -v 5.2.4.1` que es la versión que tengo que instalar o no?

**Comment by elramirezv** [comment]
Perdón jajaja eso

**Comment by elramirezv** [comment]
Qué te arroja cuando corres:  `ruby -v` y `bundler -v` ??

**Comment by tomasalvarez13** [comment]
ruby -v : `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x64-mingw32]`
bundler -v: `Bundler version 2.1.2`

**Comment by elramirezv** [comment]
Mmmmm extraño, tengo exactamente lo mismo y me funciona bien 😟 Estás en Windows?

**Comment by tomasalvarez13** [comment]
Sí, podrá ser porque instalé ruby con un installer y no mediante el terminal?

**Comment by tomasalvarez13** [comment]
Podrá ser porque instalé ruby con un installer y no mediante el terminal?

**Comment by jmndoza** [comment]
@tomasalvarez13 para evitar problemas, mejor lo instalas del terminal.. en windows creo que ahora se puede ocupar bash (terminal unix), desde Visual Studio Code (lo recomiendo) debería aparecer algo así 
![1AGtr](https://user-images.githubusercontent.com/24240983/77092988-21960e00-69e9-11ea-9a90-ad740a6f1087.png)
Ojala te sirva...

**Comment by tomasalvarez13** [comment]
Gracias, Y puedo instalar rails usando una version anterior de ruby, y despues de que esté instalado, cambiar a ruby 2.7?

**Comment by daleal** [comment]
Hola! Para todos aquellos que se encuentran con un problema similar, los invito a leer la issue #8 para resolver sus problemas :heart:

**Comment by NickCastillo** [comment]
Hola! En la guia de [Go Rails](https://gorails.com/setup/ubuntu/19.10), que tan importante seria realizar la parte de "Configuring Git"?

**Comment by daleal** [comment]
Para instalar ruby y/o rails, es irrelevante.
