### ISSUE TITLE
Duda instalación Ruby

### ISSUE THREAD

**Issue by mfortiz** [IIC2143-2020-1/proyecto#10]
Hola!
Estaba descargando Ruby desde https://gorails.com/setup/ubuntu/18.04 y usando RVM.
Pero me salió este error
![image](https://user-images.githubusercontent.com/37163461/77117152-320daf00-6a10-11ea-94df-1c4cc5920111.png)
Quería saber cómo solucionarlo 😢 , 
Muchas gracias jaja

**Comment by elramirezv** [comment]
Hola @mfortiz !

Pareciera ser un problema con la conexión. Estuve googleando el problema y al parecer es un tema recurrente en el subsystem de Ubuntu en Windows. Encontré este hilo que te podría servir:

https://forum.theodinproject.com/t/gem-installer-bundler/6732/69

Una posible solución:

> All you have to do is uncheck the IPv6 box on your network adapter from the Windows control panel (disable/enable the adapter again afterward to make sure settings apply) and then you’ll be able to ping and install gems from bash like you would normally be able to.
