### ISSUE TITLE
Problemas con username en devise

### ISSUE THREAD

**Issue by nicoguz** [IIC2143-2020-1/proyecto#102]
Hola!!
Estaba siguiendo la ayudantía al pie de la letra y todo iba perfecto hasta que llegue a la parte de agregar un campo de username. Modifiqué todos los archivos que el ayudante modificó, hice migrate y todo y por alguna razón cuando entro a http://localhost:3000/users/sign_up la vista que me muestra es exactamente igual a la de antes de agregar usuario (es decir no se agregó el campo a rellenar de username). No me tira ningún error y realmente no se donde me estoy equivocando. Es como si el archivo html.erb no se actualizara. Ayuda por favor!!!!!

**Comment by daleal** [comment]
Hola! Cuando modificaste los archivos, de casualidad modificaste una migración que ya habías migrado en vez de crear una nueva?
Cuando Rails corre `db:migrate`, lo que hace es mirar el _timestamp_ de la última vez que migró y solamente migrar archivos que sean **nuevos**. Si te fijas, los archivos de migraciones parten con un _timestamp_. Esto es para evitar realizar migraciones que ya están cambiadas en la base de datos (en aplicaciones con muchas migraciones podría tomar **mucho** rato si se migra todo cada vez). Por eso, si por ejemplo tienes un archivo de migración sobre el que ya hiciste `db:migrate`, luego lo modificas y vuelves a hacer `db:migrate`, ese archivo no será migrado de nuevo, y tu base de datos se mantendrá **estructuralmente idéntica** a como estaba antes de ejecutar ese último comando.

**Comment by JuaniAndres** [comment]
Hola a mi me paso lo mismo siguiendo los pasos no se me actualizaba el html a pesar de editarlo pero cache que el problema estaba en mi caso  que la app estaba sacando la vista en un path distinto a app/views/users. Como era otro path y no existía entonces saca las vistas de los archivos de la gema. Yo finalmente lo pude arreglar usando ``rails generate devise:views``  pero igual encuentro raro que los pasos de la ayudantia no me funciono

**Comment by nicoguz** [comment]
Si era la migración parece, reinicie la base de datos desde 0 y lo volví a hacer considerando los cambios antes de la migración y si funcionó, gracias!!!
