### ISSUE TITLE
Partición Ubuntu

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2143-2020-1/proyecto#103]
Holaa
Después de instalar la consola de Ubuntu me decidí por hacer la partición. No sé muy bien cómo hacerlo por lo que agradecería algo de guía y si me pudieran decir si tiene algún riesgo para mi pobre pc.

Gracias!

**Comment by ceosorio** [comment]
Hola, no soy ayudante pero esto es lo que yo hago:
Uso **rufus** (si estás en windows) para armar un booteable en un **USB**. De ahi te metes a tu BIOS y pones que intente primero bootear desde usb y te aparecerá ubuntu para instalar :)
Para seguir una instalación para Dual Boot, podrías ver [este link](https://askubuntu.com/questions/343268/how-to-use-manual-partitioning-during-installation)

Lo importante es decir que quieres realizar tu la partición, y ahí decidir de qué porte quieres la partición :)
