### ISSUE TITLE
Problemas con las vistas de devise

### ISSUE THREAD

**Issue by TrigalJeruti** [IIC2143-2020-1/proyecto#104]
Hola! Cree restaurants con devise pero al modificar las vistas estas no se actualizan pues me sale que se esta rendereando a devise/registrations en lugar de restaurants/ registrations. Lo que hice fue cambiar el nombre de la carpeta restaurants que tiene las vistas que modifique a devise, lo que me resulto, pero no creo que sea la mejor solución. 
Saben como puedo solucionar este problema?
De antemano muchas gracias.
P.D: Estoy trabajando en windows

**Comment by elramirezv** [comment]
Hola @TrigalJeruti !

La verdad es que no se entiende muy bien qué es lo que estás intentando hacer, podrías dar más contexto ? Ideal si es con algo de código o los errores que te tira 😄

**Comment by meretamal** [comment]
Hola 😁 !!

En el caso de que tengas [_scoped views_](https://github.com/heartcombo/devise#configuring-views), debes ingresar a **config/initializers/devise.rb** y descomentar la linea `# config.scoped_views = false` y cambiar el valor a `true`.

**Comment by TrigalJeruti** [comment]
Hola!!!!!
Muchas graciasss, me funciono perfecto la solución.
