### ISSUE TITLE
Clases grabadas Zoom

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2143-2020-1/proyecto#105]
Hola!
Estaba estudiando y me di cuenta de que no puedo ver las clases de levantamiento de requisitos. Me sale este mensaje:
"You cannot view this recording
No permission."

Si me pudieran ayudar siería genial!

**Comment by daleal** [comment]
Hola! Podrías decirme específicamente qué video del módulo de levantamiento de requisitos estás tratando de ver?

**Comment by ChayoPerez** [comment]
Hola! Ahora sí me funciona. No sé qué fue lo que pasó antes. Gracias! :)
