### ISSUE TITLE
Sincronización base de datos proyecto

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2143-2020-1/proyecto#106]
Hola! Estoy un poco perdida sobre cómo funciona la base de datos para el proyecto. Tengo postgres instalado y funcionando bien, pero no sé cómo se sincroniza con las bases de datos de mis compañeros si tengo entendido que postgres guarda las cosas de forma local.
(Perdón si es muy noob la pregunta)

Gracias!

**Comment by elramirezv** [comment]
Hola @ChayoPerez !

La sincronización se lleva con las migraciones, las cuales reflejan los cambios que se le han ido haciendo a la base de datos (pero solo a nivel de schema). Los datos que se guardan no pueden ser sincronizados, ya que como bien dices, es local. Para solucionar esto último existen las seeds, las cuales sirven para "llenar" la base de datos automáticamente (cualquiera que las ejecute tendrá "lo mismo" que tu en la base de datos).

Finalmente, la base de datos que importa es la que está en Heroku, ya que esa es la que tiene los datos que se muestran a los usuarios.

Ojalá haya quedado un poco más claro 😄
