### ISSUE TITLE
Problema con migraciones pasadas

### ISSUE THREAD

**Issue by Saveliz** [IIC2143-2020-1/proyecto#107]
Hola!
Con mi grupo hicimos lo de devise incluyendo una migración donde agregabamos parámetros a las columnas de bases de datos. Luego, creando otras tablas para manejar con CRUDs, (en otro pc), nos dice que hay migraciones pendientes:

Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate RAILS_ENV=development

Sin embargo, al hacer la migración, nos da duplication error, ya que está intentando agregar un parámetro a la tabla que ya habíamos agregado. (Este problema surge con la tabla agregada por devise.) Cabe decir que la migración ya la habíamos corrido antes, pero en el pc que se encargó de devise.

StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "username" of relation "users" already exists

Nos podrían ayudar a resolver, o a entender nuestro problema?
Muchas gracias!

**Comment by nabenitez** [comment]
Hola!

Tal como señalas con:
```
PG::DuplicateColumn: ERROR: column "username" of relation "users" already exists
```
Lo que ocurre es exactamente lo que se describe ahí y esto es producto de que la migración nueva intenta añadir una columna que ya ha sido agregada por otra.

Si las migraciones les **funcionan correctamente en otro computador** quiere decir que no están siendo consistentes entre las versiones que cada persona de tu grupo maneja. 

Por lo anterior, si quien instaló devise borró alguna migración esto genera problemas de incosistencia en la base de datos, por tal razón es **muy importante** que no borren migraciones, ya que obligan a **resetear la db**.

La solución:
```rails db:drop db:create db:migrate```

Esto eliminará la base de datos actual, creará una nueva y por último migrará todo. 

Si lo anterior no soluciona tu problema, comentalo acá mismo!

Quedo atento 😄
