### ISSUE TITLE
Problema radio button disable

### ISSUE THREAD

**Issue by Deleon20** [IIC2143-2020-1/proyecto#108]
Hola! 
Teniamos una duda a nivel de codigo que hemos buscado pero no hemos tenido mucho exito. El tema es que queremos que al clickear un radio button ciertos text_field se vuelvan grises y el usuario no pueda escribir en ellos, encontramos una funcion :onclick => "$('age').disable();" y en el text_field le pusimos <%= f.number_field :Edad, autofocus: true, autocomplete: "Edad",id:"age" %>. Al correr esto la pagina se ve bien pero no funciona lo que queremos lograr 😔.

**Comment by valerojasm** [comment]
Hola!

El selector de un id en jQuery es `#`, por lo que se debería ver así: `$('#age').disable();`. Por otro lado, recuerden que debe estar instalada dicha librería para su correcto funcionamiento.

Saludos!
