### ISSUE TITLE
Restricción de modulos tarea ruby

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2143-2020-1/proyecto#11]
Hola, hay restricción de modulos para la tarea ruby? Lo digo porque me trae flashbacks de la restricción de módulos de progra avanzada... Y también porque estaba pensando en usar el módulo csv, entre otros

**Comment by daleal** [comment]
Hola! Puedes usar `CSV` para resolver la tarea. Con respecto a otros módulos, realmente no hay restricciones, pero considerando que el objetivo principal de la tarea es que aprendan ruby (ya que no lleva una nota _per se_, recomiendo usar **solamente** `CSV` (está pensada para hacerse así)

**Comment by cchauriye** [comment]
Hola! Quiero usar esa librería, pero al haber "ñ" y tildes en los csv me tira error (probé cambiándolos y ahí si funciona). ¿Qué encoding debiese ponerle para que corra?

Gracias!

**Comment by daleal** [comment]
El encoding "utf-8" es el que te permite representar todos los caracteres _unicode_.

**Comment by cchauriye** [comment]
Es que cuando le pongo "uft-8" no me lo lee. Si le pongo "iso-8859-1", solo me cambia esos caracteres. Ninguno me tira todo completo.

**Comment by daleal** [comment]
Podrías tratar pasándole el parámetro `encoding: "ISO8859-1:utf-8"` al método (lo que eso quiere decir es que el _encoding_ externo es `ISO8859-1` y el interno es `utf-8`). Debido a que esta issue no se trata realmente de este tema, si no te funciona te pido que hagas otra issue detallando qué has hecho y qué sigue fallando.

**Comment by cchauriye** [comment]
Gracias!
