### ISSUE TITLE
Error postgres autentificacion usuario

### ISSUE THREAD

**Issue by figarcia3** [IIC2143-2020-1/proyecto#110]
Hola! Tengo este problema al iniciar el server.

![error1](https://user-images.githubusercontent.com/48328327/80776541-a1f37700-8b30-11ea-81ef-6b5085877039.png)

Tambien me da un error similar al crear un server en pgadmin

![error2](https://user-images.githubusercontent.com/48328327/80776632-d5ce9c80-8b30-11ea-9247-6ab5e23823ad.png)

**Comment by daleal** [comment]
Hola! Tu contraseña de `postgres` no es vacía?

**Comment by figarcia3** [comment]
Puede que sea vacía, pero pgadmin no me deja crear el server sin establecer una contraseña, hay alguna manera de setearla desde otro lado?

**Comment by daleal** [comment]
Estás usando Windows?

**Comment by figarcia3** [comment]
ubuntu 18.4

**Comment by daleal** [comment]
Intenta acceder a través de `psql` con el usuario `postgres` para ver si efectivamente ese usuario está guardado sin clave. Si no, puedes intentar creando otro usuario en Postgres y accediendo con ese usuario.
