### ISSUE TITLE
Restriccion gemas proyecto

### ISSUE THREAD

**Issue by ranelson1** [IIC2143-2020-1/proyecto#111]
Hola! existe alguna restriccion sobre las gemas que podemos utilizar para el projecto?

Quisiera utilizar Carrierwave y Bootsnapp-sass, pero no se si puedo

Gracias!

**Comment by daleal** [comment]
Hola! `carrierwave` si está permitida. Con la segunda te refieres a `bootstrap-sass`?

Relacionado con #112

**Comment by ranelson1** [comment]
Buenisimo gracias. Si fue un typo, me referia a esa, bootstrap-sass

**Comment by daleal** [comment]
Si puedes usarla también!
