### ISSUE TITLE
Gemas permitidas y prohibidas

### ISSUE THREAD

**Issue by daleal** [IIC2143-2020-1/proyecto#112]
Hola! Les dejo las gemas permitidas a lo largo del proyecto. Cualquier duda de gema pregúntenla en un comentario de esta issue. Iré actualizando la lista a medida que se agreguen nuevas gemas.

## Gemas permitidas

- `devise`
- `bcrypt`
- `will_paginate`
- `activeadmin`
- `cancan`
- `simple_form`
- `chartkick`
- `faker`
- `populator`
- `carrierwave`
- `bootstrap-sass`
- `bootstrap`
- `jquery-rails`
- `wicked`
- `file_validators`
- `momentjs-rails`
- `bootstrap3-datetimepicker-rails`
- `rails_admin`
- `fie`
- `mini_magick`
- `excon`
- `filterrific`
- `geocoder`

## Gemas prohibidas

- `jumpstart`

**Comment by RositaMunoz** [comment]
Hola! se puede usar la gema file_validators?
Saludos

**Comment by daleal** [comment]
@RositaMunoz si se puede!

**Comment by jmndoza** [comment]
se puede usar rails_admin ? (igual..  viene la gema en Rails por defecto)

**Comment by vicerc** [comment]
Se pueden usar estas gemas momentjs-rails y bootstrap3-datetimepicker-rails?

**Comment by daleal** [comment]
@Vicerc si puedes usar ambas gemas.

**Comment by daleal** [comment]
@jerrymendoza si puedes usar esa gema

**Comment by jtcaraball** [comment]
Hola! podemos usar Paperclip o Carrierwave para manejar las fotos de usuarios y locales? Saludos!!

**Comment by daleal** [comment]
@jtcaraball no debería ser necesario. Desde la versión `5.2`, Rails incluye algo llamado [ActiveStorage](https://guides.rubyonrails.org/active_storage_overview.html) que es exactamente para lo que sirve Paperclip (de hecho, esa gema está deprecada, como puedes ver [en el README](https://github.com/thoughtbot/paperclip/blob/master/README.md)). Recuerda almacenar las imágenes en un servicio usando algo como [Cloudinary](https://cloudinary.com/documentation/rails_activestorage) para que no se borren tus imágenes en Heroku.

**Comment by Zetaku1** [comment]
Hola! se puede utilizar la gema fie?

**Comment by daleal** [comment]
Hola! Si puedes usar la gema `fie`!

**Comment by nlecaros1** [comment]
Hola! Se puede usar la gema ```Bootstrap Filestyle```?

**Comment by pablogw** [comment]
Se puede usar la gema mini_magick?

**Comment by daleal** [comment]
@pablogw si puedes usar `mini_magick`!

**Comment by jtcaraball** [comment]
Se puede usar la gema excon?

**Comment by daleal** [comment]
@jtcaraball si puedes usar `excon`!

**Comment by ceosorio** [comment]
Hola, se puede usar la gema `filterrific`?

**Comment by daleal** [comment]
@ceosorio si puedes usar `filterrific`!

**Comment by RositaMunoz** [comment]
Hola! se puede ocupar la gema geocoding? saludos :)

**Comment by daleal** [comment]
@RositaMunoz te refieres a la gema [geocoder](https://github.com/alexreisner/geocoder)?

**Comment by daleal** [comment]
(Solamente para agilizar el proceso, **si** se puede usar `geocoder`)

**Comment by RositaMunoz** [comment]
haha sii! muchas gracias!
