### ISSUE TITLE
Duda diagrama E/R

### ISSUE THREAD

**Issue by oscars810** [IIC2143-2020-1/proyecto#113]
Hola!

Con mi grupo teníamos la siguiente duda, resulta que queremos poner botones u opciones específicas que solo aparezcan para los usuarios admin, entonces no sabemos si para trabajar será más cómodo que tenga un atributo que sea True/False si es admin o no, o hacer una "herencia" (ISA) de la tabla de usuarios para guardar solo los admins.

**Comment by elramirezv** [comment]
Hola @oscars810 !

Tienen que pensar los pros y contras que tendría cada una de las formas de modelar el problema y evaluar cual es la que mejor se ajusta a las necesidades del software.

Piensen en las consultas que tendrían que hacer en los controladores y/o la forma que tendrían que manejar las vistas.
