### ISSUE TITLE
Problema al generar migrate desde mi computador

### ISSUE THREAD

**Issue by mafernandez9** [IIC2143-2020-1/proyecto#114]
Hola! Tengo problemas al momento de hacer el rake de la migración. Me tira un error y aborta la operación. 
Cabe destacar que he tenido muchisimos problemas al momento de utilizar Rails y Ruby. Subo la foto del error que se produce

![WhatsApp Image 2020-05-01 at 13 08 10](https://user-images.githubusercontent.com/53874019/80824739-0eac5700-8bad-11ea-999f-0f48c4a08e94.jpeg)

**Comment by elramirezv** [comment]
Hola @mafernandez9 !

Al parecer podría haber un carácter en tu `database.yml` (o en `enviroment.rb` pero dudo que hayan tocado ahí) que está molestando, revisa que hayan solo letras en las variables (sin tildes/espacios/signos ni nada).

Si has tenido tantos problemas, por qué no consideras la opción de hacer una partición? :smile:
