### ISSUE TITLE
Heroku devise localhost

### ISSUE THREAD

**Issue by Pdesolmi** [IIC2143-2020-1/proyecto#115]
Hola, con nuestro grupo seguimos la ayudantía de devise y nos funciona perfecto todos los botones de registrarse, el inicio de sesión y todo en el localhost. pero una vez que hicimos el push a heroku solo nos funciona la vista principal de bienvenida y si apretamos los botones nos tira error y no se abre la pagina. No se especifica el error solo dice 'We are sorry, something went wrong'

Espero su respuesta, muchas gracias

**Comment by elramirezv** [comment]
Hola @Pdesolmi !

De casualidad corrieron las migraciones después de hacer push ?

Lo otro, pueden ejecutar: `heroku logs --tail` y ver los errores que tira la consola de Heroku :smile:

**Comment by Pdesolmi** [comment]
yo siguí la ayudantía nomás así que hice las migraciones antes, en el heroku logs no veo ningún error claro. No sabemos que hacer y por ahora estamos trabajando en el localhost nomás

**Comment by valerojasm** [comment]
Intenten correr las migraciones de nuevo en heroku, y en caso de que eso no funcione, boten la base de datos y corranlas desde cero.

**Comment by raimundoloeser** [comment]
Muchas gracias, ahi funciono
