### ISSUE TITLE
Gitflow

### ISSUE THREAD

**Issue by lothardp** [IIC2143-2020-1/proyecto#116]
Hola! 
En el enunciado de la entrega 1 donde dice "Seguir la filosofía de Gitflow para gestionar tu repositorio", se refiere a seguir específicamente la metodología gitflow que sale explicada en la wiki? o solo a seguir las recomendaciones de commits atomicos, buenos mensajes, etc. Y lo otro, esto también es evaluado?
Gracias!

**Comment by valerojasm** [comment]
Hola!

Se refiere a seguir la metodología, es decir, uso correcto de branches. Por otro lado, también nos interesa que todos los miembros del equipo estén constantemente haciendo commits (en el fondo no puede haber solo uno subiendo sus avances a Github). Respecto a las recomendaciones, son solo eso, sin embargo es bueno que las sigan, en general en cualquier trabajo formal son lineamientos que se respetan.

Saludos 😸
