### ISSUE TITLE
Problema en application.html.erb

### ISSUE THREAD

**Issue by mpsubiabre** [IIC2143-2020-1/proyecto#119]
Hola, al correr la aplicacion con 'rails server' me aparece el siguiente error en 'app/views/layouts/application.html.erb':

![image](https://user-images.githubusercontent.com/42593773/81323373-46ab1280-9063-11ea-8781-5e3dc175bea2.png)

No entiendo que esta pasando, busque y no logre arreglarlo. Gracias!

**Comment by mpsubiabre** [comment]
Lo arregle escribirndo en el archivo ApplicationController.rb, layout false bajo la clase. No entiendo porque pero funciono

**Comment by daleal** [comment]
Usar `layout = false` tendrá como consecuencia que no se carguen tus assets. Esta issue es un duplicado de #79.
