### ISSUE TITLE
[Tarea 0] Base de datos de prueba

### ISSUE THREAD

**Issue by FeBalla** [IIC2143-2020-1/proyecto#12]
¿Es posible que se nos suba eventualmente una **base de datos de prueba** para probar el funcionamiento de nuestro código? Obviamente que tuviera sentido con el enunciado y que cumpla con las condiciones y sintáxis requeridas.
¡Gracias!

**Comment by daleal** [comment]
Hola! Por supuesto, dentro de esta primera semana les subiremos un set de archivos `.csv` para que puedan usarlo :tada:

**Comment by JJJGGGG** [comment]
Hola, cuando van a subir estos archivos? Gracias!
