### ISSUE TITLE
Problemas con helpers para rutas

### ISSUE THREAD

**Issue by mpsubiabre** [IIC2143-2020-1/proyecto#120]
Hola! Al hacer el edit de un CRUD me sale el siguiente error, como si no reconociera el @taste siendo que se define anteriormente en el def edit del controller

![image](https://user-images.githubusercontent.com/42593773/81358373-53038f80-90a4-11ea-9f4a-723c0dbb98b0.png)

**Comment by valerojasm** [comment]
Hola!

El método patch utiliza la ruta para una instancia específica, en este caso, `taste_path(:id)`, la que recibe el `id` del gusto que quieres y aplica alguna acción (leer/editar/eliminar/etc). Lo que dice tu error es que esa ruta o método no existe. Revisa con `rail routes` cuáles tienes disponibles.

**Comment by valerojasm** [comment]
Hola!

El método patch utiliza la ruta para una instancia específica, en este caso, taste_path(:id), la que recibe el id del gusto que quieres y aplica alguna acción (leer/editar/eliminar/etc). Lo que dice tu error es que esa ruta o método no existe, o en su defecto no está definida para ese objeto. Revisa si está dicha ruta con `rail routes` y revisa que le estás pasando un objeto de `taste` y no una query o clase.

**Comment by mpsubiabre** [comment]
sii, lo tengo el routers: 
![image](https://user-images.githubusercontent.com/42593773/81363427-4a658600-90b1-11ea-82ee-eadeb1fe77a9.png)

y si le estoy pasando un objeto:
![image](https://user-images.githubusercontent.com/42593773/81362919-002fd500-90b0-11ea-8daa-4a51623b75d8.png)
pero no entiendo cuando se le asigna el path, por ejemplo el error que sale, que efectivamente le falta una s, nunca se la asigne y tampoco se donde cambiarla por lo mismo.
En el file routers le entrego la acción de update:
![image](https://user-images.githubusercontent.com/42593773/81363554-9d3f3d80-90b1-11ea-91b3-cd772f486da8.png)
 Afectara que no tengo los controller en singular?
Gracias!!

**Comment by daleal** [comment]
Hola! Si te fijas, tienes definida la ruta `tastes` para la acción HTTP `POST`, pero lo que está tratando de encontrar Rails es la ruta `taste` (nota cómo una ruta tiene una `s` y se refiere a la colección completa y la ruta que te falta no tiene la `s` y se refiere solamente a un recurso de la colección).

Como Rails es un _framework_ al que le gusta la _magia_ :sparkles:, al usar el _helper_ `form_with` se espera que las rutas estén nombradas de ciertas formas específicas. Puedes nombrarlas a mano, pero Rails es majestuoso y te ofrece una forma para [hacerlo automáticamente](https://guides.rubyonrails.org/routing.html#resource-routing-the-rails-default) usando _recursos_. Te recomiendo leer esa sección de la documentación (es relativamente corta) para entender un poco más cómo funcionan los _helpers_ de rutas de Rails.

**PD**: está bien que tus _controllers_ no estén en singular, es el _Rails Way_

**Comment by mpsubiabre** [comment]
Gracias !!
