### ISSUE TITLE
Heroku deploy

### ISSUE THREAD

**Issue by JuanDlugo** [IIC2143-2020-1/proyecto#122]
Llevamos mucho tiempo intentando solucionar este problema  para subir la app a Heroku.
Al principio pensamos que era porque la aplicación no tenia el Buildpack de Ruby, pero luego lo instalamos y de igual manera nos vuelve a tirar el mismo error.
Buscamos muchas soluciones en internet pero ninguna pudo con el problema
Por favor si alguien sabe de que podría tratarse o si le paso lo mismo subiendo sus app
¡Gracias!

![Captura de Pantalla 2020-05-08 a la(s) 15 55 48](https://user-images.githubusercontent.com/48494298/81444297-e68c9d00-9144-11ea-8ea1-64840431eaa0.png)

**Comment by daleal** [comment]
Hola! Si en la misma carpeta ejecutas `ls`, qué te sale?

**Comment by JuanDlugo** [comment]
![Captura de Pantalla 2020-05-08 a la(s) 16 08 35](https://user-images.githubusercontent.com/48494298/81445036-2dc75d80-9146-11ea-8500-d3f3960b5764.png)

**Comment by daleal** [comment]
Me podrías decir qué hay en tu `.gitignore`?

**Comment by JuanDlugo** [comment]
creo que no tenemos .gitignore
al menos al hacer cat .gitignore me dice 
No such file or directory

**Comment by daleal** [comment]
Ya, ya sé cual es el problema. Lo que pasa es que cuando ejecutas `git push heroku master`, lo que hace `git` es buscar una carpeta `.git` en la carpeta en que ejecutas el comando. Si no la encuentra, sube al _parent directory_ a buscar la carpeta `.git` y así hasta que la encuentra (si es que existe). Apenas encuentra la carpeta, **toma la carpeta donde encuentra a `.git` para subir el repositorio al remote de Heroku**. Como en su proyecto en la raíz del repositorio no está la app, lo que está tratando de buildear Heroku es un repositorio que en una de sus sub-carpetas tiene la app (esto obviamente falla). Lo que deberían hacer es tener la app completa en la raíz del repositorio y las cosas como documentos de entregas o archivos por el estilo dejarlos en una carpeta llamada `docs` (también ubicada en la raíz de su repositorio).

**Comment by JuanDlugo** [comment]
Buenísimo muchas gracias! Pero no me quedo muy claro una parte, las carpetas de app y docs tienen que estar donde las coloque en la imgen (Si realizo git remote -v en ese directorio no me aparece heroku, solo origin). O ambas dentro de grupo29-proyecto donde en git remote -v si me aparece heroku.
Mil gracias por todo y sorry por el cachito te pasaste!

![Captura de Pantalla 2020-05-08 a la(s) 16 34 42](https://user-images.githubusercontent.com/48494298/81447309-68cb9000-914a-11ea-9ab9-f8ec37611e06.png)

**Comment by daleal** [comment]
Para eso estamos!

Lo que debería pasar es que cuando ejecutes `ls` dentro de `grupo29-proyecto` te salga un resultado más o menos así:

```
app
bin
config
db
docs
lib
log
node_modules
public
storage
test
tmp
vendor
babel.config.js
config.ru
Gemfile
Gemfile.lock
package.json
postcss.config.js
Rakefile
README.md
yarn.lock
```

**Comment by JuanDlugo** [comment]
Me sigue tirando el mismo error inicial :/

**Comment by daleal** [comment]
Tienes que hacer `git add` y `git commit` (recuerda que estás mandando un repositorio de `git` a otro _remote_, es como tratar de hacer `git push` a GitHub sin haber _commiteado_ nada).

**Comment by vicentesh** [comment]
Hola Dani, Juano se fue a una prueba por lo que continué yo con el Deploy y ya lo logré solucionar, al final como nos dijiste que no teníamos el .git, era por que no habíamos realizado el git init dentro de la carpeta de la app, lo hice y funcionó. Muchísimas gracias, te pasaste 😄

**Comment by daleal** [comment]
Tener una carpeta `.git` dentro de un repositorio que ya es repositorio de `git` puede ser **muy** problemático. Te recomiendo mover todo lo de la app a la raíz del repositorio si es posible, pero que bueno que funcionó!
