### ISSUE TITLE
Error al correr el servidor

### ISSUE THREAD

**Issue by MatiasBarraF** [IIC2143-2020-1/proyecto#123]
Cree una nueva aplicación para probar cosas y al crear el servidor me aparece el siguiente error. ¿Como podría arreglarlo? Busqué en google y no sale mucho. El sistema operativo es MacOS.
![image](https://user-images.githubusercontent.com/48270008/81452085-f8297100-9153-11ea-9d86-bd585ccc10d3.png)

**Comment by daleal** [comment]
Si ejecutas el comando `cat /etc/hosts`, qué retorna?

**Comment by MatiasBarraF** [comment]
![Screen Shot 2020-05-08 at 18 02 12](https://user-images.githubusercontent.com/48270008/81452886-142e1200-9156-11ea-8790-57a0f347542b.png)

**Comment by daleal** [comment]
Puedes ver si hay algo en `tmp/pids`?

**Comment by MatiasBarraF** [comment]
Nop, no hay nada

**Comment by daleal** [comment]
Está extraño tu error. Prueba con la última respuesta de [este link](https://stackoverflow.com/questions/28768934/rails-server-cannot-start-getaddrinfo-nodename-nor-servname-provided-or-not-k)
