### ISSUE TITLE
Problema con scaffold

### ISSUE THREAD

**Issue by amyaranta** [IIC2143-2020-1/proyecto#124]
Hola, estoy intentando crear una entidad con scaffold, pero me apacere el siguiente mensaje: /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- puppet (LoadError)
He buscado en internet, pero no he encontrado ninguna respuesta concreta.
Muchas gracias

**Comment by daleal** [comment]
Me podrías decir qué sistema operativo usas?

**Comment by amyaranta** [comment]
elementary hera 5.1

**Comment by daleal** [comment]
Que interesante! Jajajajajajajaja
Y tienes instalado `node` en tu máquina?

**Comment by amyaranta** [comment]
sip

**Comment by amyaranta** [comment]
Además me acabo de dar cuenta que al hacer rails server me sale el mismo error y ya no corre
Edit: tampoco puedo  usar los otros comandos de rails
Edit 2: borrando scaffold puedo volver a usar los comandos rails

**Comment by daleal** [comment]
A qué te refieres que borrando scaffold puedes volver a usar los comandos de rails?
