### ISSUE TITLE
Problema migraciones pendientes 

### ISSUE THREAD

**Issue by nicru** [IIC2143-2020-1/proyecto#125]
Hola, decidí instalarme Ubuntu para tener menos problemas con la app y resulta que no puedo correrla porque no me deja hacer las migraciones.

Adjunto pantallazo del error:
![localhost error](https://user-images.githubusercontent.com/48329013/81479685-be5b7780-91f2-11ea-87e2-623767ab9f4d.png)
![Terminal](https://user-images.githubusercontent.com/48329013/81479686-bf8ca480-91f2-11ea-9f80-7dc65e3476dd.png)

**Comment by elramirezv** [comment]
Ya está solucionado, lo que pasó aquí fue que había una migración llamada `CreateCitas` y el modelo que intentaban crear dentro de la migración se llamaba `Cita`, entonces fallaba porque le faltaba la "s" al modelo 😄
