### ISSUE TITLE
Problema con rails server

### ISSUE THREAD

**Issue by etoteiza** [IIC2143-2020-1/proyecto#126]
Hola! utilizando mi app (cualquiera) en la que creo como db posgresql, al hacer rails server me aparece el siguiente error sobre una contraseña. Es raro, ya que no me ha pasado antes utilizando la misma db.

<img width="1220" alt="Screen Shot 2020-05-13 at 10 04 51" src="https://user-images.githubusercontent.com/48265731/81822493-31216700-9501-11ea-9774-6f3fececedd1.png">

**Comment by meretamal** [comment]
Hola 😁 !!

Podrías revisar esta issue y ver si te funciona? #46
