### ISSUE TITLE
Solver tarea ruby

### ISSUE THREAD

**Issue by niguzman** [IIC2143-2020-1/proyecto#132]
Hola,
estaba tratando de usar el método normal para revisar el output de mi tarea pero me sale esto "sh: 1: solver.sh: not found" y no cacho por qué es 
(Lo estoy corriendo dentro de la carpeta solver)

**Comment by daleal** [comment]
Hola! Me podrías decir exactamente qué comando estás ejecutando?

**Comment by niguzman** [comment]
Pongo sh y luego solver.sh

**Comment by daleal** [comment]
Ok, entonces estás ejecutando `sh solver.sh` y te sale `sh: 1: solver.sh: not found`. Podrías mandar el output del comando `ls`?

**Edit**: También podrías intentar corriendo `sh ./solver.sh`

**Comment by niguzman** [comment]
![image](https://user-images.githubusercontent.com/48304981/82847271-35fbf880-9ebb-11ea-95d3-0c2784191bc4.png)

Con el comando del edit me sale lo sgte:
![image](https://user-images.githubusercontent.com/48304981/82847289-50ce6d00-9ebb-11ea-9d53-29741b5cb550.png)

**Comment by daleal** [comment]
Y si ejecutas solamente `./solver.sh`? (Perdón por esto, me imagino que debe ser por diferencias en nuestros lenguajes de consola)
