### ISSUE TITLE
Cambio version rails

### ISSUE THREAD

**Issue by MatiasBarraF** [IIC2143-2020-1/proyecto#134]
Estaba tratando de cambiar la versión 6 que tengo de Rails por la 5.2. Al instalar la 5.2 ningún problema, pero al tratar de desinstalar la versión 6 me aparece el siguiente error. Al correr el comando que te dicen tampoco funciona. ¿Alguna idea de cómo puedo arreglarlo?
![image](https://user-images.githubusercontent.com/48270008/83209211-c178c200-a125-11ea-8dc9-421afec71872.png)

**Comment by daleal** [comment]
Probablemente se deba a que tienes más de una versión de ruby instalada y hayan conflictos por eso. En cualquier caso, solo debería ser necesario especificar la versión de rails en el `Gemfile` para que se use esa versión en específico (no es necesario instalar las gemas en tu computador, ya que `bundle install` instala las gemas necesarias para el proyecto en un directorio especial y luego las usa cuando ejecutes comandos sobre esas gemas en el directorio con el repositorio).

**Comment by MatiasBarraF** [comment]
Perfect!
