### ISSUE TITLE
Error en formulario post

### ISSUE THREAD

**Issue by sluchsinger** [IIC2143-2020-1/proyecto#136]
El form que hice es el siguiente:
```
<%= form_with(model: @chat, method: :post) do |form| %>
    <div class="field">
        <%= form.label :mensaje, class: "label" %>
        <%= form.text_field :mensaje, class: "input is-small" %>
    </div>
    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>
```
y me aparece el error:
```
undefined method `to_model' for #<ActiveRecord::Relation []>
Did you mean?  to_xm
```
no entiendo las soluciones que me he buscado, ni cual es el problema 
gracias de antemano

**Comment by sluchsinger** [comment]
parece que el problema esta en el modelo chat porque si le pongo otro el formulario si me aparece, pero no se cual es el problema con ese modelo

**Comment by elramirezv** [comment]
Hola @sluchsinger !

Qué le estás pasando al formulario en `@chat`? Me parece que le estás entregando un array vacío 😮

**Comment by sluchsinger** [comment]
Si lo solucioné y era justo eso, muchas gracias igual
