### ISSUE TITLE
Asosiacion: doble referencia a una misma tabla.

### ISSUE THREAD

**Issue by oscars810** [IIC2143-2020-1/proyecto#138]
Hola!

En nuestro modelo de match guardamos dos id de usuario, por lo que al hacer la asosiacion hicimos:

```ruby
belongs_to :user1_id, class_name: 'User'
belongs_to :user2_id, class_name: 'User'
```

Entonces quería saber como sería hacer el equivalente a `user.matches` para mostrar todos los match de un usuario. No se si hay que especificar si queremos los match asosiados a user1_id o user2_id, o algo del estilo porque cuando usamos `user.matches` rails nos tira error y dice que tal vez intentaba llamar a `user.matches.user1_id` pero cuando hacemos eso vuelve a tirar otro error.

**Comment by elramirezv** [comment]
Hola @oscars810 !

Relacionando User y Match con un `has_many: matches` debería funcionar.

Por otro lado, también podrías hacer algo como `match.where(user1_id: user)`. 😁

**Comment by oscars810** [comment]
Gracias!
