### ISSUE TITLE
Ponderación notas

### ISSUE THREAD

**Issue by folozano** [IIC2143-2020-1/proyecto#139]
Hola!

He buscado en los archivos del curso pero no he podido encontrar la ponderación de los distintos ítems en la nota final. 

Me refiero a un documento en donde se explicita el valor porcentual de cada evaluación, algo del tipo:

Entrega 1 - 15% nota proyecto
Entrega 2 - 35% nota proyecto
...
I1 - 25% nota cátedra 
...

Nota final = (0,4 * nota cátedra) + ...

Agradecería mucho si me pudieran decir dónde puedo encontrar esto.

**Comment by daleal** [comment]
Hola! El programa especifica cómo se estructura la nota de cátedra (I1, I2 y Examen) y cómo ésta se articula con la nota del proyecto, pero no habla sobre el proyecto en si.

## Proyecto

- <a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;\small&space;\overline{E}_P" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\inline&space;\small&space;\overline{E}_P" title="\small \overline{E}_P" /></a>: Promedio de notas de entregas parciales
- <a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;\small&space;E_F" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\inline&space;\small&space;E_F" title="\small E_F" /></a>: Nota de entrega final, como producto desarrollado
- <a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;\small&space;P_F" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\inline&space;\small&space;P_F" title="\small P_F" /></a>: Nota de presentación final
- <a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;\small&space;NF" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\inline&space;\small&space;NF" title="\small NF" /></a>: Nota final del proyecto


<a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;\LARGE&space;NF&space;=&space;0.5&space;\cdot&space;\overline{E}_P&space;&plus;&space;0.2&space;\cdot&space;E_F&space;&plus;&space;0.3&space;\cdot&space;P_F" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\inline&space;\LARGE&space;NF&space;=&space;0.5&space;\cdot&space;\overline{E}_P&space;&plus;&space;0.2&space;\cdot&space;E_F&space;&plus;&space;0.3&space;\cdot&space;P_F" title="\LARGE NF = 0.5 \cdot \overline{E}_P + 0.2 \cdot E_F + 0.3 \cdot P_F" /></a>

## Cátedra

La nota final de cátedra (<a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;\small&space;NI" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\inline&space;\small&space;NI" title="\small NI" /></a>) es un promedio entre las dos interrogaciones y el examen.

## Nota final

La nota final es un promedio entre <a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;\small&space;NF" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\inline&space;\small&space;NF" title="\small NF" /></a> y <a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;\small&space;NI" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\inline&space;\small&space;NI" title="\small NI" /></a>. Notar que se necesita pasar la cátedra y el proyecto por separado para aprobar el ramo.

**Comment by folozano** [comment]
Gracias!
