### ISSUE TITLE
Contenido columnas archivos csv

### ISSUE THREAD

**Issue by clementesepulveda** [IIC2143-2020-1/proyecto#14]
Hola,
tengo una duda a que representan los datos de vuelos y paises del archivo pasajeros.csv, y el de sector de habitantes.csv. Los numeros son el id de los vuelos, paises y sectores respectivamente?

**Comment by daleal** [comment]
Hola! Cada habitante puede tener solo 1 sector, por lo que esa columna contiene un número con el `id` del sector al que pertenece cada habitante. Con respecto a vuelos y paises, esa columna corresponde a números separados por `:` donde cada número corresponde al `id` de un vuelo que en el que estuvo el pasajero (en el caso de los vuelos) o al `id` de un país que visitó el pasajero (en el caso de los paises).

**Comment by DiegoEmilio01** [comment]
Hola, pueden cambiar las columnas de los .csv? Es decir, asumimos el orden del enunciado o debemos procesar la primera linea para saber el orden de las columnas?
Muchas gracias de antemano.

**Comment by elramirezv** [comment]
Hola @DiegoEmilio01!

Puedes asumir el orden que aparece en el enunciado 😄
