### ISSUE TITLE
NoMethodError en user.rb

### ISSUE THREAD

**Issue by Ignaciomendezp** [IIC2143-2020-1/proyecto#140]
En mi modelo de 'user' definí una función 'x' la que me devuelve una lista.
Para comprobar que la función estuviera funcionando, abrí la consola de rails, seleccioné un usuario y llamé a la función (usuario.x). Luego, en la consola me aparece lo siguiente:
NoMethodError (undefined method `x' for #<User::ActiveRecord_Relation:0x00007fa547e0e8d8>). 😥

**Comment by elramirezv** [comment]
Hola @Ignaciomendezp !

¿Cómo estás llegando a hacer `usuario.x`? Puede ser que la instancia esté dentro de un Array y por eso no encuentre el método. Te funciona si haces `usuario.first.x` ?

**Comment by Ignaciomendezp** [comment]
Si, me funciona

**Comment by Ignaciomendezp** [comment]
A que te refieres que este dentro de un array la instancia?

**Comment by elramirezv** [comment]
Por la forma de la consulta, puede ser que te esté retornando algo como `[instancia]`. Entonces al hacer `[instancia].first`, te quedaría la `instancia` en la variable. (Es lo mismo que hacer `[instancia][0]`)
