### ISSUE TITLE
Modificar componentes de Bulma

### ISSUE THREAD

**Issue by benito-tondreaux** [IIC2143-2020-1/proyecto#141]
Holaa!!

Tengo una duda de como cambiar las variables de pagination en bulma, para poder cambiar el estilo de este componente, ¿Como puedo importar las variables de Bulma en mi application.css para poder cambiarlas?.

Estuve leyendo la issue #131, por lo que en un comentario leí que se debía importar las variables, ¿Me podrías ayudar por favor?.

**Comment by daleal** [comment]
Hola! Para poder cambiar las variables de bulma, debes estar usando archivos `.scss`. En esos archivos puedes llegar y escribir una línea `$variable = 'newval';` que altera el valor de `$variable`
