### ISSUE TITLE
instanciar dos clases simultaneamente

### ISSUE THREAD

**Issue by mpsubiabre** [IIC2143-2020-1/proyecto#142]
Hola! Nos pasa que al registrarse un usuario se pide en el formulario que ingrese la comuna a la cual pertenece. Hicimos las asociaciones correspondientes entre estos dos modelos(“user belongs to: zone “ y “zone has many: users”), sin embargo, tenemos el problema de no poder instanciar la zona ingresada antes de registrar al usuario. Nos sale el siguiente error:
![image](https://user-images.githubusercontent.com/42593773/83655698-b215d080-a58c-11ea-8fe2-5b848408b597.png)
Esto sucede ya que user está modelado con atributo el id de la zona (zone_id), por lo que necesitamos que la zona se cree (si no existe) y luego entregarle al user el id de esta zona creada para así poder registrarse correctamente. De existir esta zona, que se entregue el id correspondiente.
¿Como lo podremos resolver? Hemos buscado sin éxito 😢

**Comment by elramirezv** [comment]
Hola @mpsubiabre !

Y si crean las comunas antes en forma de seed ? Así las comunas ya partirían pobladas.

**Comment by mpsubiabre** [comment]
Muchas gracias! Puse las comunas en el seed y luego en las vistas use collection_select para que se pudiesen seleccionar, por la consola puedo ver que si se envía el id correspondiente 
![image](https://user-images.githubusercontent.com/42593773/83666488-03c55780-a59b-11ea-9771-180d45a3fa23.png)
pero aun asi me sale el mismo error de que la zona no existe:
![image](https://user-images.githubusercontent.com/42593773/83666700-5a329600-a59b-11ea-9168-b1645cacc3a5.png)

**Comment by elramirezv** [comment]
Quizás sea porque no le estás pasando correctamente el `id` de la comuna al momento de crear el usuario (en el controlador) ?? Si te fijas bien, el `zone_id` viene dentro de una key `invoice`.

**Comment by mpsubiabre** [comment]
Ese era el problema, muchas gracias! ahora si pude solucionar :smile:
