### ISSUE TITLE
Devise y update user

### ISSUE THREAD

**Issue by Ignaciomendezp** [IIC2143-2020-1/proyecto#147]
Hola! Estoy teniendo dudas acerca de cómo funciona bien Devise. Devise genera una serie de views en la carpeta users. Es recomendable que realizemos nuestras views de iniciar sesión, registrarse, editar perfil, etc. en estas views? De ser asi (:sweat:), como relaciono los submit buttons al controlador que cree (perfil_controller)?  Trate de implementar mi edit del usuario en la carpeta registrations/edit, pero al hacer submit en esa view no se me esta guardando ningún dato que edito del usuario, asumo que es porque no esta relacionado con mi controlador perfil#update, pero no entiendo como lo puedo relacionar. :cold_sweat:

**Comment by valerojasm** [comment]
Hola!

Devise te ayuda con el **manejo de sesiones y registro** de un modelo en particular, en este caso lo usamos para los usuarios. Como bien dijiste, para iniciar sesión, registrarse y editar tus datos puedes ocupar los mismos recursos que la gema te crea, lo único que te faltaría (por lo que te entendí) es poder mostrar la información de ese usuario que creaste/editaste en un perfil. Para esto, debes crear un controlador para el modelo usuarios (si es que no lo tienes previamente) de manera que puedas crear otros métodos y rutas sobre esta entidad. A través de este nuevo método que crearás, que recibirá el `id` de un usuario, traerás toda su info desde la BD y la enviarás a una view en particular, en este caso el perfil. Ahora, si quieres que esta misma view tenga la opción de editar este perfil, vas a tener que redirigir al usuario a la ruta que nos permite editar registros, y esa pertenece a las que creó devise 😄 Se entiende? Avísame si hay algo que no quedó muy claro. Éxito!

**Comment by Ignaciomendezp** [comment]
O sea que mi controlador perfil (que ya tiene implementado los metodos de edit, update, etc. no me servirá? Otra cosa no me queda muy claro :sweat_smile:, una vez tengo este nuevo controlador, cómo redirijo las acciones (submit buttons) de las views generadas por devise a los metodos de este nuevo controlador?

**Comment by valerojasm** [comment]
Tu controlador perfil está asociado a un modelo perfil? Cuéntame de esto.

Los submit de las views de devise que nombras gatillan las acciones update y create, o sea: crear una nueva sesión, crear un nuevo registro o editar un registro existente. Esos no deberías querer cambiarlos: si quieres tener en tu página de perfil de usuario (asociada a una ruta y método de tu otro controlador) que diga "Edita tu perfil", vas a usar los métodos de devise, porque quieres editar un registro existente.

TL;DR: Tu controlador nuevo solo debería tener un método show, porque devise se encarga de new, create, edit, etc. En este show, si quieres que el usuario pueda editar su info, rediriges a la ruta update de devise para ese usuario 😸

**Comment by Ignaciomendezp** [comment]
Tengo un modelo `users` y no de `perfil`, y en controladores tengo `perfil` pero no `users` :confused: . No se si estan relacionados o no :sweat_smile: , como se ve eso? Es recomdable que elimine el controlador perfil y deje solo el de users para que quede todo mas ordenado?
