### ISSUE TITLE
Gema para imágenes

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2143-2020-1/proyecto#148]
Hola! Mi equipo y yo estamos atascados en encontrar una gema que funcione con Heroku. Sin querer perdimos tiempo usando una que no era compatible.  Nos podrían dar un ejemplo de una buena por favor?

Gracias! Saludos

**Comment by daleal** [comment]
Hola! Desde la versión `5.2`, Rails incluye algo llamado [ActiveStorage](https://guides.rubyonrails.org/active_storage_overview.html) que entrega una interfaz simple para almacenar archivos como imágenes desde tu código. Para almacenar las imágenes en Heroku y que no se borren te recomiendo quizás usar algo como [Cloudinary](https://cloudinary.com/documentation/rails_activestorage).

**Comment by JuanDlugo** [comment]
Hola, aprovechando la issue quería preguntar si les sirvió la gema Cloudinary?
Lo que pasa es que ya tenía funcionando ActiveStorage localmente y ahora estoy intentando implementar Cloudinary. Pero a la hora de mostrar la foto en la View, al usar el método url_for("user.foto"), me devuelve un link que cuando lo "imprimo" en la View no muestra nada.
Cualquier respuesta sería de gran ayuda. 
;)

**Comment by daleal** [comment]
Si entras al link desde el browser, ves la imagen que subiste?

**Comment by JuanDlugo** [comment]
ahhh me aclaraste! Estaba imprimiendo el link como un string, ahora probé y sí efectivamente, puse  link_to( el link anterior) y si lo apreto veo la foto
Ahora como podría imprirla sin la necesidad de apretar el link?

**Comment by JuanDlugo** [comment]
ahhh no te preocupes ahí lo logre! por si alguien lo necesita es un image_tag con adentro el url de la foto ;)
Muchas gracias!
