### ISSUE TITLE
Array como atributo

### ISSUE THREAD

**Issue by isiguelfand** [IIC2143-2020-1/proyecto#149]
Hola!
Para el proyecto estoy tratando de hacer que mi modelo Match tengan dos listas/arreglos con fechas, y que cada lista sea un atributo. Sin embargo, no me está funcionando. No sé si tal vez haya una manera "correcta" de hacerlo. Actualmente  mi modelo tiene lo siguiente:
`    t.datetime "fecha_matched", default: [], array: true
    t.datetime "fecha_matcher", default: [], array: true`
La única otra forma que se me ocurre para solucionar esto es crear otro modelo Fecha, y crear las asociaciones correspondientes. Sin embargo, habría que crear también las tablas intermedias y no creo que haga sentido hacer esto para una simple lista de números...

**Comment by valerojasm** [comment]
Hola Isidora!

Si bien puedes serializar datos para que un atributo se comporte como un arreglo, en una base de datos relacional esto **no corresponde a una buena práctica**. En una no relacional (usando por ejemplo, mongoDB) no habría problemas. Para hacer lo que quieres existen las **asociaciones**, si quieres me puedes explicar qué quieres hacer específicamente para poder guiarte mejor, sin embargo por lo que pude notar yo creo que necesitarás una tabla intermedia.

**Comment by isiguelfand** [comment]
Muchas gracias! Si entiendo que generalmente se necesitan asociaciones, pero en este caso creo que sería complicar algo que es bastante simple. Quiero que cada usuario que hizo match, pueda agregar una fecha (o varias) a ese match, para que sean las fechas en las que se encuentra disponible para una cita (la fecha estaría en formato date). Para eso necesito (creo) dos listas de fecha (cada una como un atributo), en mi modelo match. Sé que la otra opción es crear un modelo Fecha, pero como Match tendría un has_and_belongs_to_many con dos fechas distintas (una por cada usuario), la tabla para relacionarlos no es tan simple.

**Comment by valerojasm** [comment]
Yap, en ese caso hay un par de caminos que pueden complicarte menos, evitando una asociación N:N y que se mantienen alineados con lo que te contaba antes.

1. Crear un modelo fecha que pertenezca a un usuario y a un match (belongs_to User / belongs_to Match), quedando de la forma `Date(date, user_id FK, match_id FK)` - donde la PK (fuera del id implícito que genera ActiveRecord) sería la tupla completa bajo las correctas validaciones, por lo que pueden haber múltiples filas para el mismo match o para el mismo user sin arriesgar unicidad. De esta forma, luego puedes consultar esta tabla agrupandola por cualquiera de esos atributos, dígase buscar todas las filas en `Date` tales que, para un match cualquiera, `match_id = match.id`, o tales que `match_id = match.id` y `user_id = match.user1`, etc.

2. Usar `composed_of`, un [método de clase](https://api.rubyonrails.org/classes/ActiveRecord/Aggregations/ClassMethods.html#:~:text=Active%20Record%20implements%20aggregation%20through,of%20%5Ban%5D%20address%E2%80%9D.) que implementa agregación, sin embargo no se usa activamente y tendrías que limitar el número de fechas a elegir por cada usuario.

La modelación depende totalmente de ustedes, así que les dejo de todas maneras un poco de documentación respecto a [serializar atributos](https://blog.arkency.com/2014/10/how-to-start-using-arrays-in-rails-with-postgresql/). Espero que les sirva la info ya sea para implementar alguna opción o también para inspirarse, dependiendo del resto de su esquema puede que encuentren algo más eficiente. 

Cuéntame si te quedan dudas. Saludos! 😸
