### ISSUE TITLE
[Tarea 0] Cuarentena

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2143-2020-1/proyecto#15]
En el enunciado, la parte de Modelación dice que debe haber un un método Cuarentena(), el cual retorna un bool, pero en ninguna parte posterior explican que hacer con ese metodo o como hacerlo. Según lo que lei mas adelante, en la parte de Aclaraciones Importantes, ahi se habla de si es que una persona debe o no hacer cuarentena, pero no lo asocian con el metodo Cuarentena(), entonces mi pregunta es que hacer con ese metodo, ya que puedo hacer que revise si una persona debe o no hacer cuarentena (revisar las aclaraciones y ver si las cumple o no) o solo mostrar si es que la persona debe hacer cuarentena (tener ya revisado por otra parte si es que una persona debe hacer o no cuarentena y solo hacer display del resultado).

Si todavia no se entiende a lo que quiero llegar, practicamente es si es que el metodo Cuarentena debe hacer todo el calculo sobre la cuarentena o puedo tener el calculo hecho desde antes y solo mostrar el resultado.

**Comment by daleal** [comment]
Hola! Realmente en la modelación hay una sugerencia de cómo estructurar tu código. Lo que sugiere el enunciado es que tengas un método que compute para cada habitante si está o no en cuarentena dadas las condiciones en las que se encuentra y lo mismo para los pasajeros. Sin embargo, eres libre de hacerlo de otra manera si eso te acomoda, siempre y cuando eso no altere los resultandos esperados.
