### ISSUE TITLE
Error eliminar user

### ISSUE THREAD

**Issue by Ignaciomendezp** [IIC2143-2020-1/proyecto#151]
Hola, estoy teniendo el siguiente error al eliminar un usario (desde la vista creada por devise). He tratado de buscar el error, pero nada parece ayudarme, queria saber donde podría estar ocurriendo este error. 😥 
![Captura de Pantalla 2020-06-22 a la(s) 15 09 21](https://user-images.githubusercontent.com/48481728/85326707-b8b4ab00-b49b-11ea-96c0-1c89d57ce949.png)

**Comment by valerojasm** [comment]
Hola Ignacio!

Necesito un poco más de información para poder ayudarte, me puedes mostrar un screenshot de lo que tienes en la vista donde estás intentando eliminar el usuario y también del controlador?

Si prefieres hacerlo de manera privada te dejo mi mail: varojasm@uc.cl

**Comment by Ignaciomendezp** [comment]
Otra cosa, a mis compañeros de grupo si les resulta eliminar un usuario. Probe reseteando mi base de datos y me sigue pasando lo mismo 👀
