### ISSUE TITLE
Fecha entrega Sprint 3

### ISSUE THREAD

**Issue by niguzman** [IIC2143-2020-1/proyecto#152]
Hola,
Quería saber si hay alguna opción de considerar una extensión del plazo para el Sprint 3. Se que la semana siguiente son los Sprint Review por lo que pensaba que la extensión podría ser hasta sábado o domingo.
En lo personal estas últimas semanas han sido non-stop con entregas y pruebas de diversos ramos (y creo que somos varios así). Esta pequeña _extensión_ de la fecha de entrega nos serviría mucho para poder entregar algo aún mejor y más completo.

Gracias 😀

**Comment by daleal** [comment]
Hola! Considerando la carga que han tenido en general los ramos este último período de tiempo, me parece justo extender la entrega **hasta el domingo 28 de junio a las 23:59**. En breve enviaré un anuncio y actualizaré los enunciados con las fechas corregidas. Mucho ánimo! :heart:
