### ISSUE TITLE
Form dinámico dependiente del valor de un dropdown

### ISSUE THREAD

**Issue by DanielaCorral** [IIC2143-2020-1/proyecto#153]
Hola, con mi grupo queremos hacer un form para citas en el cual yo elija un local desde un dropdown y automáticamente se actualice un time_field que como mínimo y maximo tenga las horas de apertura y cierre del local seleccionado en el dropdown. Hemos buscado mucho y por lo que podemos ver, tiene mucha relación con js, cosa que no manejamos bien. ¿Alguna idea de como lograr esto?

Muchas gracias!

**Comment by daleal** [comment]
Hola! Comprendo su idea. Sin embargo, como el ramo no es un ramo enfocado en frontend, mi recomendación es la siguiente: en el mismo dropdown, pongan texto con horas de apertura y cierre (por ejemplo, una opción podría decir `Starbucks (8:30 - 19:30)`, otra podría decir `DCCafé (9:30 - 22:00)`, etc) y chequeen desde el backend que el horario elegido en el `time_field` sea válido para el local. Les recomiendo esto porque la entrega es relativamente pronto y puede ser un poco complicado implementar lo que explicaste si nunca has usado JavaScript.

En todo caso, si realmente estan muy empeñadas en lograrlo, háganlo! Pero como es un problema más práctico que conceptual, la manera más eficiente de recibir ayuda para esto sería pidiendo ayuda a su _Product Owner_ por telegram o algo similar (para que la comunicación sea más fluida y le sea más fácil revisar su código).

**Comment by DanielaCorral** [comment]
Gracias por las recomendaciones! No se nos había ocurrido, así que lo intentaremos!
