### ISSUE TITLE
CSS Heroku

### ISSUE THREAD

**Issue by JuanDlugo** [IIC2143-2020-1/proyecto#154]
Hola! Tengo un pequeño problema. Localmente mi app funciona super bien con los css correspondientes. Pero al subirla a Heroku, estos archivos no se cargan. Probémoos varias soluciones que encontré en internet como en aplicacation.rb colocar:
    config.serve_static_assets = true
    config.assets.initialize_on_precompile = false
También  incluir una gem 'rails_12factor' o incluso correr heroku run rails assets:precompile (el cual me tiro error).
Bueno en definitiva la app sigue sin css styling. Cualquier recomendación o ayuda me serviría mucho, 
Gracias!!

**Comment by daleal** [comment]
Hola! Me podrías decir qué error hubo cuando corriste `heroku run rails assets:precompile`? Una solución, en todo caso, sería correr localmente `rails assets:precompile` antes de hacer `git push heroku master`

**Comment by JuanDlugo** [comment]
Si había corrido ese comando antes(rails assets:precompile). Lo volví a intentar recién luego de un nuevo commit y no funcionó.
Por otro lado al ejectutar el "heroku run rails assets:precompile" me tira un error de Syntax de tipeo en un el archivo yarn:
- "/app/bin/yarn: 4: /app/bin/yarn: Syntax error: "(" unexpected"

**Comment by daleal** [comment]
Cuando precompilaste los assets antes de subir la app a heroku, tenías activado `config.serve_static_assets = true`? Y los assets compilados están dentro del control de versiones (git) o están ignorados?

**Comment by JuanDlugo** [comment]
Si y si (creo)!
Ya que si los lee cuando hago lo siguiente: 
La única solución que por el momento he encontrado es incluir en el mismo archivo html.erb el styling.
Sé que es una muy mala practica, pero si hago eso funciona.

**Comment by daleal** [comment]
Te recomiendo **nunca** poner estilo en el HTML. Cuando ejecutaste `rails assets:precompile` y cambiaste `config.serve_static_assets` a `true`, hiciste un commit antes de hacer `git push heroku master`? Recuerda que heroku hace básicamente lo mismo que hace GitHub

**Comment by JuanDlugo** [comment]
Sii hice un commit antes, de hecho cuando me lo dijiste lo intenté de nuevo y tampoco funcionó.
Si, leí que es una muy mala practica :/
Pero seguiré buscando info mientras tanto.
Gracias igualmente

**Comment by JuanDlugo** [comment]
![Captura de Pantalla 2020-07-08 a la(s) 00 33 56](https://user-images.githubusercontent.com/48494298/86876482-d47e9a80-c0b2-11ea-9372-500be4d294b0.png)

Pregunta, alguien sabe que podría causar este error? Lei en internet que desde rails 5.2 ya no se usa secrets.yml sino que tu master-key esta encriptada en credenciales.yml.enc. Ahora no se como acceder a esta clave y/o como entregársela a el ambiente de producción.
Si alguien tiene la mas mínima idea estaría agradecido 😄 
jajajaja

**Comment by daleal** [comment]
Por favor, haz una issue distinta para discutir ese problema. Gracias!

**Comment by JuanDlugo** [comment]
Lo solucioné, por si a alguien también le llega a pasar ahora subiendo su app mi problema era el siguiente:
primero actualizar mi versión de Yarn y luego en el archivo package.json deben explicitarle a Heroku que versión de Yarn están utilizando para precompilar. En mi caso agregue lo siguiente:

```json
"engines": {
    "yarn": "1.22.4"
}
```
