### ISSUE TITLE
Nota Catedra

### ISSUE THREAD

**Issue by jtcaraball** [IIC2143-2020-1/proyecto#156]
Hola! Viendo que el examen ya no es reprobatorio, se mantendra que se remueva la peor nota entre las interrogaciones y el examen?

Saludos!

**Comment by daleal** [comment]
Hola! El examen reemplaza la peor nota >= 3. Es decir, si tuvieras las siguientes notas:

I1: 2.0
I2: 3.0
Ex: 4.0

Tu promedio se calcularía como (I1 + 2 * Ex) / 3

**Comment by daleal** [comment]
Hola! El examen reemplaza la peor nota >= 3. Es decir, si tuvieras las siguientes notas:

I1: 2.0
I2: 3.0
Ex: 4.0

Tu promedio se calcularía como (I1 + 2 * Ex) / 3
