### ISSUE TITLE
Error de instalación

### ISSUE THREAD

**Issue by mpbascunan** [IIC2143-2020-1/proyecto#16]
Holaa, estaba siguiendo la guía de instalación que enviaron y en la parte "Installing the Linux Subsystem for Windows" dice que hay que ejecutar "bash" para instalar Bash on Ubuntu on Windows, sin embargo cuando selecciono bash, se abre y se cierra al instante, y no hace nada más. No sé porqué sucede esto, hay algún otro paso que debería hacer?

**Comment by elramirezv** [comment]
Hola @mpbascunan!

Dado que la instalación del subsystem es independiente de la instalación de Ruby y Rails, quizás podrías  intentar hacer la instalación con esta [guía](https://docs.microsoft.com/en-us/windows/wsl/install-win10) y luego seguir con la guía de [Go Rails](https://gorails.com/setup/windows/10).

Cabe mencionar también que en la guía de Go Rails se menciona: 

> This only works on 64-bit installations of Windows.

Si tu computador es de 32-bit no te funcionará, quizás sea eso? Avísanos si te funciona!

**Comment by mpbascunan** [comment]
Me funcionó, graciaas

**Comment by clolate** [comment]
Hola encontré en [https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/](url) por qué no se instalaba el **bash** de ubuntu según la guía que mandaron,  
![imagen](https://user-images.githubusercontent.com/37159005/78420079-32b66000-7622-11ea-9ad6-06c7e1d597f9.png)
como me pasó lo mismo busqué más y efectivamente lo encontré en la _Microsoft store_ y ahí queda instalado

por si alguien quiere tenerlo :)
