### ISSUE TITLE
Fecha interrogaciones

### ISSUE THREAD

**Issue by DiegoEmilio01** [IIC2143-2020-1/proyecto#17]
Hola en la clase introductoria del curso aparecen las evaluaciones y sus ponderaciones, pero no las fechas. (Hay unas en buscacursos pero no confio mucho en esa info.) Muchas gracias de antemano.

**Comment by daleal** [comment]
Hola! Debido a la situación en la que se encuentra el :earth_americas:, se decidió no subir un calendario que **sin duda** va a cambiar. En vez de eso, las evaluaciones se avisarán _en runtime_ (obviamente con tiempo).
