### ISSUE TITLE
[Tarea 0] método cuarentena

### ISSUE THREAD

**Issue by pedro919** [IIC2143-2020-1/proyecto#18]
Hola! Puedo hacer que el método "cuarentena" de la clase Pasajero reciba atributos? 
Sería más o menos así:
pasajero.cuarentena(hash)
Se puede, cierto?

**Comment by daleal** [comment]
Hola! Puedes modelar el programa como gustes! Lo que importa es que tome los archivos especificados, los procese y genere el archivo de _output_ esperado!
