### ISSUE TITLE
Install webpacked

### ISSUE THREAD

**Issue by cristobaltaverne** [IIC2143-2020-1/proyecto#19]
Hola! cuando ingreso rails webpacker:install me tira error y en este aparece: "node" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"nodejs" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
Node.js not installed. Please download and install Node.js https://nodejs.org/en/download/
porque podrá ser esto? ya probé descargando node js
Gracias de antemano

**Comment by elramirezv** [comment]
Hola @cristobaltaverne !

¿Por qué estás intentando instalar `webpacker`?

De todas maneras, instalando `nodejs` debería de funcionar. Qué te arroja si ejecutas `node --version` ?

**Comment by daleal** [comment]
Hola! Me puedes confirmar que estás usando `rails 6`? El proyecto debe ser realizado con `rails 5.2`, que no requiere `webpacker`

**Comment by cristobaltaverne** [comment]
Lo estaba instalando porque el profesor lo paso en la clase y pense que era necesario para el proyecto, cuando pongo node --version me aparece v12.16.1. A ya gracias voy a ocupar rails 5.2 nomas
