### ISSUE TITLE
Duda ayudantía ARGV y gets

### ISSUE THREAD

**Issue by daleal** [IIC2143-2020-1/proyecto#2]
Hola! Durante la ayudantía de `ruby` de la sección 1 alguien preguntó por qué al usar `ARGV` la función `gets` no funciona correctamente y le dije que respondería en una issue. Lo que sucede en este caso es que la función `gets` **no necesariamente** recibe datos desde [stdin](https://en.wikipedia.org/wiki/Standard_streams). De hecho, `gets` lee desde `$<`, que, en caso de que `ARGV` esté vacío, será `stdin`, pero si no, será `ARGV`. En términos simples, si `ARGV` tiene algo dentro, `gets` intentará abrir el archivo con nombre `ARGV[0]` y leer la primera línea. Si `ARGV` no tiene nada dentro, pedirá que se le entregue un input (porque recibirá datos de `stdin`).

Pueden probar esto ustedes mismos! Escriban el siguiente archivo y llámenlo `test.rb`:

```rb
variable = gets.chomp
puts variable
```

Ahora, corran `ruby test.rb`. Como `ARGV` está vacío, les pedirá su input. Si, en cambio, corren `ruby test.rb test.rb`, `ARGV[0]` será `test.rb`, por lo que `gets` leerá el archivo y retornará la primera línea. El error visto durante la ayudantía se debió a que `ARGV[0]` no correspondía a ningún archivo (algo así como correr `ruby test.rb wenawena`). Si quisieran usar `ARGV` y también `gets` desde `stdin`, lo más recomendable es guardar sus datos de `ARGV` en variables y después correr `ARGV.clear`. Así, `gets` volverá a usar `stdin`.

Por último, les dejo una duda existencial (pueden resolverla probando)... ¿Qué sucedería si ponen dos `gets` y corren el script usando algún `ARGV`? Algo así como esto:

```rb
# Complex file
variable_1 = gets.chomp
variable_2 = gets.chomp
puts "#{variable_1} ---------- #{variable_2}"
```

**Comment by JuaniAndres** [comment]
hola @daleal  van a subir los archivos de la ayudantia en algún lugar como para practicar editando?

**Comment by daleal** [comment]
Hola! Como se dijo en la ayudantía, en este momento puedes encontrarlos en [el primer link de la sección de Ruby de la wiki](https://github.com/IIC2143-2020-1/proyecto/wiki/Ruby-y-Ruby-on-Rails), pero prontamente copiaré los archivos a su propia carpeta en el repositorio oficial del curso.

**Comment by JuaniAndres** [comment]
Yap muchas gracias
