### ISSUE TITLE
Archivo output.txt

### ISSUE THREAD

**Issue by fcartoni** [IIC2143-2020-1/proyecto#20]
Hola! 
Cuando se ejecutan las intrucciones, como pueden ser más de una, se debe generar un archivo de output para cada instrucción? O solo un archivo de output que tenga contenga la resolución de todas las instrucciones?

**Comment by elramirezv** [comment]
Hola @fcartoni !

Solamente un archivo de output para todas las instrucciones :smile:

**Comment by gicrot** [comment]
Hola!
Yo tengo otra duda con respecto al archivo output, al momento de escribir este archivo con las distintas resoluciones, ¿estas van a ir pegadas una tras otra o puede haber un salto de línea entre medio?

Por ejemplo:
...
*** FIN HABITANTES EN CUARENTENA ***
<salto de línea>
*** COMIENZO PERSONAS EN CUARENTENA ***
...

**Comment by elramirezv** [comment]
Hola @gicrot !

Tienen que ir pegadas una tras otra 😄

**Comment by lisraelrat1** [comment]
Hola! Con respecto a este mismo tema, en el enunciado dice que pueden haber instrucciones repetidas. En el archivo de output se tiene que escribir una vez cada instrucción, es decir, eliminando las repetidas al leer? O solo seguir las instrucciones independiente de si se escribe por ejemplo 4 veces el output de pasajeros_en_cuarentena?

**Comment by elramirezv** [comment]
Hola @lisraelrat1!

La respuesta está en #36 :smile:
