### ISSUE TITLE
ayudantias 

### ISSUE THREAD

**Issue by camaruri** [IIC2143-2020-1/proyecto#21]
Hola, las ayudantías las van a subir grabadas a alguna parte?
Por lo menos a mi me cuesta mucho seguirlas tan rápido, serviría mucho poder verlas después y pararlas.
Gracias

**Comment by daleal** [comment]
Hola! En un principio no, más que nada debido a que no estaba planeado. Sin embargo, han solicitado bastante que sean subidas, por lo que estoy evaluando cómo hacerlo lo más simple posible para el cuerpo de ayudantes para poder subir el material grabado.
