### ISSUE TITLE
Version PostgreSQL

### ISSUE THREAD

**Issue by oscars810** [IIC2143-2020-1/proyecto#22]
Hola, solo quería saber que versión de postgre hay que instalar o da lo mismo.

**Comment by daleal** [comment]
Hola! En general las nuevas versiones de postgres se enfocan en añadir funcionalidades extremadamente avanzadas que no usaremos ni remotamente en este ramo. Por lo mismo, la versión es irrelevante. Si no tienen instalado el programa y deben elegir una versión, recomiendo elegir la versión 12.2, debido a que es la versión que viene por default en la base de datos de Heroku, pero realmente no importa.
