### ISSUE TITLE
Parte de Metodos Tarea 0

### ISSUE THREAD

**Issue by perezpefaur** [IIC2143-2020-1/proyecto#23]
En el metodo pasajeros_en_cuarentena() no nos especifican que este recibe algo. Entonces nose como empezar este metodo. Lo que me haria sentido que reciba una lista con objetos tipo pasajeros/habitantes para saber si estan en cuarentena o no. 

Gracias de antemano

**Comment by elramirezv** [comment]
Hola @perezpefaur !

No es necesario que esta función reciba algo. Los pasajeros vienen definidos a partir del archivo `pasajeros.csv`, por lo que desde ahí tienes que crear tu lista de objetos.

**Comment by perezpefaur** [comment]
Aaah buenisimo! Gracias!

**Comment by perezpefaur** [comment]
Estos archivos no se han subido o si? Que no lo encuentro. 
Si no se ha subido, los van a subir eventualmente?

**Comment by elramirezv** [comment]
No, aún no están arriba. A penas los subamos daremos el aviso :smile: 

Cabe mencionar que la estructura (columnas) será la misma que la mencionada en el enunciado, así que puedes basarte en eso para avanzar con la tarea :+1: .

**Comment by mfortiz** [comment]
Eso quiere decir que en cada función (pasajeros_en_cuarentena, habitantes_en_cuarentena, personas_en_cuarentena,...etc) tengo que instanciar los archivos csv correspondientes?

Gracias.

**Comment by daleal** [comment]
Significa que para la ejecución de los métodos, necesitarás usar los datos de los archivos `.csv`. Recomiendo, en cualquier caso, instanciarlos en modelos en su código y luego usar los necesarios dependiendo de la función a ejecutar (para no tener que estar cargando datos cada vez que se llame una función).
