### ISSUE TITLE
Citar código

### ISSUE THREAD

**Issue by Dnpoblete** [IIC2143-2020-1/proyecto#24]
Hola, tengo la duda de si es necesario citar código que ocupemos de alguna página o si no es necesario? En el caso de ser necesario cómo tendría que hacerlo?

Muchas gracias 😄

**Comment by nabenitez** [comment]
Hola!, 
Siempre es necesario. Basta con que pongas el link de de la fuente en un comentario dentro del código. 
😄

**Comment by Dnpoblete** [comment]
Oka, gracias! 😄
