### ISSUE TITLE
Duda Aclaraciones importantes

### ISSUE THREAD

**Issue by Zetaku1** [IIC2143-2020-1/proyecto#25]
Cuando nos dicen

> Un habitante solo tiene un sector
> Un Pasajero no puede repetir vuelos ni paises
> Un vuelo puede tener días_de_vuelo >= 0

Que se espera que realicemos?
Es decir, podría ignorar a los objetos que vengan con datos defectuosos, o por ejemplo en el caso de los habitantes establecer el primer sector como valido y olvidar el resto. Por ultimo podría poner a los objetos defectuosos en cuarentena, cual es la mejor forma de actuar con estos casos?

Lo ultimo que supongo es que estos datos nos ayudan para no tener que preocuparnos de casos defectuosos.
Entonces cuando dicen
>Un habitante solo tiene un sector

No me debo preocupar de que en los datos vengan habitantes de mas de un sector.

**Comment by daleal** [comment]
Hola! La idea de esas aclaraciones es para que no manejen casos borde en que un habitante tenga varios sectores. Es decir, **puedes asumir que aquellas condiciones se van a cumplir en los datos que les entreguemos**.

**Comment by Zetaku1** [comment]
Gracias!
