### ISSUE TITLE
Duda funcionamiento Ruby

### ISSUE THREAD

**Issue by jalliende** [IIC2143-2020-1/proyecto#26]
Hola tengo una duda de funcionamiento de Ruby, por que al escribir el código de esta manera me tira un resultado:
![image](https://user-images.githubusercontent.com/48294819/77378967-3f9b9f80-6d56-11ea-994c-c16e58fc6b2f.png)
pero al imprimir b directamente me tira este error:
![image](https://user-images.githubusercontent.com/48294819/77379033-6954c680-6d56-11ea-97f8-07d6d5ffbb7c.png)
es por que estoy imprimiendo objetos? 
muchas gracias de antemano

**Comment by daleal** [comment]
Hola! Lo que yo veo es un error de sintaxis en la línea de `puts` en la segunda imágen, pero no veo el error en esa línea en el código, por lo que probablemente hay algún error de sintaxis en otra parte (en teoría deberían imprimir lo mismo)

**Comment by daleal** [comment]
Encontré el problema. Aparentemente `puts` no es capaz de parsear el diccionario sin los paréntesis del método, por lo que `puts { "uno": x, "dos": y, "tres": z }` se cae. Sin embargo, si lo corres como `puts({ "uno": x, "dos": y, "tres": z })`, todo funciona bien (y debería imprimir lo mismo que tu otro `puts`).

**Comment by jalliende** [comment]
Gracias!
