### ISSUE TITLE
Duda Modelación Tarea

### ISSUE THREAD

**Issue by jalliende** [IIC2143-2020-1/proyecto#27]
Hola, me surgió una duda de la modelación. Pro ejemplo, cuando hablamos de la clase Pasajero que tiene el atributo vuelos, este necesariamente es una lista con instancias de la clase Vuelo o puede ser solo el id de un vuelo. Muchas gracias de antemano. Y cuando se señala el método cuarentena => bool significa que este retorna un bool o podemos no hacerlo retornar nada (y que "active la cuarentena") y acceder al atributo que queramos con un accessor?

**Comment by daleal** [comment]
Queda totalmente a tu criterio. Piensa qué crees que sería más útil de tener y modelalo así.

**Comment by jalliende** [comment]
Gracias
