### ISSUE TITLE
Especificación de atributos de pasajero

### ISSUE THREAD

**Issue by troncosoae** [IIC2143-2020-1/proyecto#29]
Hola, 
Tengo una duda sobre los atributos tipo lista de la clase Pasajero. 
El enunciado dice : 
vuelos: List[Vuelo]
paises: List[Pais]

Mi pregunta es si el atributo vuelos necesariamente tiene que ser una lista de _objetos tipo Vuelo_, o puede ser una lista de _ids de Vuelos_. 
Pregunto porque intuitivamente me hace más sentido que un pasajero tenga como atributo una lista de ids. 

Y repito la pregunta en el caso de la lista de Paises.

Gracias!

**Comment by elramirezv** [comment]
Hola @atroncoso2 !

En #27 está la respuesta :smile:
