### ISSUE TITLE
macOS: RVM + Ruby

### ISSUE THREAD

**Issue by daleal** [IIC2143-2020-1/proyecto#3]
Hola! Varios alumnos me han comentado que no han podido instalar `rvm` en macOS Catalina siguiendo los pasos del [link recomendado](https://rvm.io/). Aquí escribiré una pequeña guía para instalar `rvm` y `ruby`. **Disclaimer**: ninguna guía puede satisfacer a todas las configuraciones existentes, inevitablemente. Les recomiendo que, si a lo largo de esta guía la consola les arroja un error, **lo googleen**. Probablemente alguien más ya lo ha tenido antes y se puede resolver con un comando. Empecemos!

Lo primero que haremos será descargar las herramientas que necesitaremos para instalar `rvm`. Usaremos [homebrew](https://brew.sh/) para instalar estas herramientas. El comando es el siguiente:

```bash
brew install curl gnupg2
```

`curl` es una herramienta para hacer descargass a través de la línea de comandos y `gnupg2` es una herramienta para encriptar y firmar archivos.

Ahora, instalaremos las llaves usadas para verificar la instalación:

```bash
gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
```

**Este comando puede cambiar!** Para asegurarse de estar usando las llaves correctas, usen las que se encuentran en [este link](https://rvm.io/rvm/install#install-gpg-keys).

Por último, descargamos `rvm` e instalamos la versión estable:

```bash
curl -sSL https://get.rvm.io | bash -s stable
```

Con esto, `rvm` debería estar instalado! Cierren la consola, abran una nueva y corran `rvm -v`. El resultado de ese comando debería ser algo como `rvm 1.29.9 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]`.

Ahora solo queda instalar `ruby` usando `rvm`!

```bash
rvm install ruby-2.6.5
```

Ya deberían poder usar ruby!

**Comment by pedrobihan** [comment]
Hola, tengo un problema con el paso a paso que está arriba. El segundo paso dice:

Ahora, instalaremos las llaves usadas para verificar la instalación:
gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB


Cuando corro eso en el terminal me arroja lo siguiente:

Warning: Failed to set locale category LC_NUMERIC to es_CL.
Warning: Failed to set locale category LC_TIME to es_CL.
Warning: Failed to set locale category LC_COLLATE to es_CL.
Warning: Failed to set locale category LC_MONETARY to es_CL.
Warning: Failed to set locale category LC_MESSAGES to es_CL.
gpg: recepción del servidor de claves fallida: No route to host


Por favor alguna ayuda de que puedo hacer para arreglarlo!

**Comment by daleal** [comment]
Hola! Las líneas que dicen `Warning` no son realmente un problema. Sin embargo, por alguna razón el comando `gpg` no es capaz de resolver el `host`. Ejecuta el siguiente comando y pega el resultado: `host pool.sks-keyservers.net`.

**Comment by pedrobihan** [comment]
Gracias por responder tan rápido, al correr lo que me dijiste me retorna lo sig.

pool.sks-keyservers.net has address 85.119.82.209
pool.sks-keyservers.net has address 24.134.103.65
pool.sks-keyservers.net has address 194.94.127.122
pool.sks-keyservers.net has address 87.118.95.9
pool.sks-keyservers.net has address 169.229.226.65
pool.sks-keyservers.net has address 192.146.137.140
pool.sks-keyservers.net has address 192.146.137.141
pool.sks-keyservers.net has address 145.100.186.254
pool.sks-keyservers.net has address 188.212.101.67
pool.sks-keyservers.net has address 194.95.66.28
pool.sks-keyservers.net has IPv6 address 2607:f140:8801::1:65
pool.sks-keyservers.net has IPv6 address 2a01:4f8:c2c:19a3::1
pool.sks-keyservers.net has IPv6 address 2a01:4f8:1c17:5140::1
pool.sks-keyservers.net has IPv6 address 2001:ba8:1f1:f2d4::2
pool.sks-keyservers.net has IPv6 address 2620:128:2000::371b:8858:51f1:5681
pool.sks-keyservers.net has IPv6 address 2001:67c:26b4:ff00::141
pool.sks-keyservers.net has IPv6 address 2001:738::600:216:3eff:fe02:42
pool.sks-keyservers.net has IPv6 address 2001:470:de7a:10::
pool.sks-keyservers.net has IPv6 address 2a02:168:f405::37
pool.sks-keyservers.net has IPv6 address 2a02:c207:3004:6520::1

**Comment by daleal** [comment]
Ok, intenta corriendo el siguiente comando:

```bash
gpg --keyserver hkp://85.119.82.209 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
```

**Comment by pedrobihan** [comment]
retorna esto:

Warning: Failed to set locale category LC_NUMERIC to es_CL.
Warning: Failed to set locale category LC_TIME to es_CL.
Warning: Failed to set locale category LC_COLLATE to es_CL.
Warning: Failed to set locale category LC_MONETARY to es_CL.
Warning: Failed to set locale category LC_MESSAGES to es_CL.
gpg: /Users/pedrobihanvelasco/.gnupg/trustdb.gpg: se ha creado base de datos de confianza
gpg: clave 105BD0E739499BDB: clave pública "Piotr Kuczynski <piotr.kuczynski@gmail.com>" importada
gpg: clave 3804BB82D39DC0E3: clave pública "Michal Papis (RVM signing) <mpapis@gmail.com>" importada
gpg: Cantidad total procesada: 2
gpg:               importadas: 2

**Comment by daleal** [comment]
Todo bien entonces! El comando se ejecutó correctamente.

**Comment by pedrobihan** [comment]
Buenísimo te pasaste! ahora sigo instalando el paso a paso de arriba a partir del paso 3 entonces?

**Comment by daleal** [comment]
Exacto

**Comment by pedrobihan** [comment]
Muchas gracias por todo, la última pregunta, ¿con esto también queda listo lo de Rails? o ahora tengo que descargar Rails por mi cuenta

**Comment by daleal** [comment]
Esto es solo ruby, rails es una gema de ruby, debes instalarlo de manera separada.

**Comment by jtcaraball** [comment]
Hola! Al tratar de instalar las llaves (usando el comando del link) el terminal retorna: "gpg: keyserver receive failed: No route to host" D:

**Comment by daleal** [comment]
Como puedes observar algunos comentarios más arriba, a @pedrobihan le pasó lo mismo, por lo que probablemente puedes seguir el mismo curso de acción.

**Comment by jtcaraball** [comment]
Ahi funcionó perfecto. Dejo el comentario arriba para que las generaciones futuras aprendan de mi error y no pregunten cosas que ya se respondieron. Muchas gracias!!
