### ISSUE TITLE
Problema instalando Rails en WLS

### ISSUE THREAD

**Issue by ceosorio** [IIC2143-2020-1/proyecto#30]
Hola, estoy teniendo un problema tratando de instalar rails en el Linux subsystem. Tengo Ubuntu 18.04, y logré instalar bien Ruby pero al momento de intentar instalar rails me sale el siguiente error:

`ERROR:  Could not find a valid gem 'rails' (= 5.2.4.1), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://rubygems.org/specs.4.8.gz)`

Usé este comando para instalarlo:

`gem install rails -v 5.2.4.1`

¿Que se puede hacer para arreglarlo? o tendré que instalar una partición de Ubuntu y tratar desde ahí?
Saludos!

**Comment by daleal** [comment]
Hola! El problema parece ser un problema con tu conexión a internet. Te recomiendo reiniciar tu computador y volver a intentarlo.

**Comment by elramirezv** [comment]
En #10 hay un link que dejé que te podría funcionar. Si bien hablan de la gema `bundler`, me parece que la solución es aplicable a cualquiera.

**Comment by ceosorio** [comment]
Hola!

@daleal y @elramirezv123 ya intenté ambas soluciones pero sigue tirando el mismo error :(

**Comment by daleal** [comment]
Debe ser algún tipo de problema en el mapeo de los servicios de _networking_ de Windows a Linux. Como el problema es extremadamente único como para poder ofrecerte una solución, lo que te recomendaría sería instalar WLS y volver a instalarlo (quizás alguna configuración no se llevó a cabo correctamente la primera vez).

**Comment by ceosorio** [comment]
Al final decidí hacer una partición con Ubuntu y me funcionó perfecto. Igual nunca supe cual era el error, en internet las soluciones que habían tampoco me funcionaron :/
