### ISSUE TITLE
Modularización

### ISSUE THREAD

**Issue by Dnpoblete** [IIC2143-2020-1/proyecto#31]
Hola, no se si ya lo habrán dicho o no, pero tengo la duda de si para esta tarea es obligatorio que todo este en el archivo main.rb o si la idea es modularizar para que sea más ordenado. Y en el caso de que se pueda modularizar estuve buscando pero no entiendo como ejecutar un método de otro .rb que importe al main.rb.

Gracias y quedo atenta a la respuesta 😄

**Comment by daleal** [comment]
Hola! Puedes modularizar todo lo que quieras (y de hecho te lo recomiendo).
Para usar métodos de otro módulo, puedes decir `require_relative 'modulo'` en tu `main.rb` y ya puedes usar las funciones de `modulo.rb` en `main.rb`.

**Comment by Dnpoblete** [comment]
Gracias, si ya estoy haciendo eso, pero mi duda era como llamar al método que quiero usar, y ya cache que se llama el método como es, pensaba que había que hacer algo así como modulo.metodo y no me funcionaba jajaja

**Comment by daleal** [comment]
Noo, `require_relative` importa completo el _namespace_ público en el módulo en que se llama

**Comment by Dnpoblete** [comment]
Oka, gracias!
