### ISSUE TITLE
Datos de archivos

### ISSUE THREAD

**Issue by furzuadr** [IIC2143-2020-1/proyecto#32]
Hola!
En las listas de países y vuelos, pueden haber ids que no existan? por ejemplo si hay solo vuelos 0,1,2, puede decir que se usó el 3 y que mi programa tenga que ignorarlo? O sólo serán valores que sí existan?
Gracias!

**Comment by elramirezv** [comment]
Hola @furzuadr !

Tal como dice en el enunciado, solo habrán ids que sí existan 😄
