### ISSUE TITLE
Llamar a atributo de una clase

### ISSUE THREAD

**Issue by furzuadr** [IIC2143-2020-1/proyecto#33]
Hola!
La única forma para llamar a un atributo dentro de una clase es haciendo dentro de la clase una función:
```
def atributo
    @atributo
 end
```
Y luego obtenerla haciendo:
`clase.atributo`
O hay otra forma? Porque cada vez que trato sin hacer la función dentro que retorne el atributo, me dice que no existe el método, aunque estoy tratando de llamar un atributo.
Gracias!

**Comment by daleal** [comment]
Hola! Eso es porque los atributos son por _default_ **privados**. Puedes usar un `:attr_accessor` para poder acceder a los atributos externamente.
