### ISSUE TITLE
Duda extensión archivos

### ISSUE THREAD

**Issue by Dnpoblete** [IIC2143-2020-1/proyecto#34]
Hola, tengo una duda con respecto a las extensiones de los archivos, podemos asumir que los archivos de data siempre serán .csv y que el de instrucciones y output sean .txt o puede ser que nos cambien la extensión?

Muchas gracias y quedo atenta a la respuesta :smile:

**Comment by elramirezv** [comment]
Hola @Dnpoblete !

Si, puedes asumir que las extensiones **no** van a cambiar 😄

**Comment by Dnpoblete** [comment]
Gracias!
