### ISSUE TITLE
Comando Corrección Tarea

### ISSUE THREAD

**Issue by gicrot** [IIC2143-2020-1/proyecto#35]
Hola!

Estaba viendo el enunciado y no me queda clara la parte de ejecución que dice que ocuparan el sgte. comando para ver la tarea:

ruby main.rb {datasets_folder} {instructions_file} {output_file}

No entiendo como definir esas cosas en mi programa para ocuparlas en este. ¿¿Onda debo definir 3 gets que en orden van a ser el dataser_folder, otro el instructions_file y otro el output_file y para ocupar estos nombres o como podría llamarlos desde el programa??

**Comment by elramirezv** [comment]
Hola @gicrot !

Estas son parámetros entregados por consola. Tal como dice en el enunciado, un ejemplo podría ser: 

`ruby main.rb data instructions.txt output.txt`. 

En el repositorio de [`ruby-examples`](https://github.com/daleal/ruby-examples/blob/master/03_argvs.rb) de @daleal hay un ejemplo de como obtenerlos dentro de tu programa 😄

**Comment by JuanDlugo** [comment]
Una pregunta relacionada al tema. La parte de data, ¿será un un nombre de alguna de las datasets? por ejemplo "small_dataset" 
O solo dirá "small"
Gracias!

**Comment by daleal** [comment]
Siempre será el nombre completo. Si le pasas `small`, es porque la carpeta con los datasets se llamará `small`, **no** `small_datasets`.
