### ISSUE TITLE
Archivo instrucciones.txt

### ISSUE THREAD

**Issue by absoto4** [IIC2143-2020-1/proyecto#36]
Hola, en el enunciado dice que el archivo con instrucciones tendrá una por cada línea, pero que puede haber repetidas o que no estén todas, y que el orden será arbitrario. Mi duda es respecto a las repetidas. ¿Qué se espera del programa? ¿Hay que ignorarlas? Gracias!

**Comment by elramirezv** [comment]
Hola @absoto4 !

Por simplicidad, que se repitan 😄
