### ISSUE TITLE
Error instalación Rails app

### ISSUE THREAD

**Issue by Juanvg213** [IIC2143-2020-1/proyecto#37]
Hola, al momento de instalar la nueva aplicación de Rails mediante la consola me entrega este error:

> An error occurred while installing sqlite3 (1.4.2), and Bundler cannot continue.
Make sure that `gem install sqlite3 -v '1.4.2' --source 'https://rubygems.org/'`
succeeds before bundling.

No logro descifrar lo que debo hacer para continuar con la instalación de la app. ¿Qué tengo que hacer?

**Comment by meretamal** [comment]
Hola!! SQLite se usa para el manejo de la base datos de tu aplicación y se utiliza por default al crear un nuevo proyecto de Rails (y es probable que te levante ese error porque no lo tienes instalado localmente).

Para el proyecto semestral vamos a estar utilizando PostgreSQL, por lo tanto, al crear la app, agrega `--database=postgresql` y asegurate de tener la versión 12.2 instalada en tu computador.

Dime si se soluciona :grin:

**Comment by Juanvg213** [comment]
¡Muchas Gracias! Funcionó perfecto.
