### ISSUE TITLE
Duda Clase 1 Introducción a Rails

### ISSUE THREAD

**Issue by ranelson1** [IIC2143-2020-1/proyecto#38]
Hola! Estaba siguiendo la clase del profesor y cuando ejecuto lo que él hace acá https://youtu.be/URsmSE7SEaY?t=3421 (57:31)

Me aparece el siguiente error 
![image](https://user-images.githubusercontent.com/53798928/77553074-16ccf480-6e93-11ea-8081-2efbf849f469.png)

Estoy ocupando Windows 10, corriendo el servidor en PowerShell, ocupando SublimeText3, y rails 5.2

**Comment by ranelson1** [comment]
Algo pasa con mi controlador que no es capaz de renderear la vista hello.html.erb

**Comment by elramirezv** [comment]
Hola @ranelson1 !

Puedes subir lo que tienes en `greetings_controller.rb` y en `config/routes.rb` ?

**Comment by ranelson1** [comment]
![image](https://user-images.githubusercontent.com/53798928/77574146-666de900-6eb0-11ea-950f-a90f19a513be.png)

**Comment by elramirezv** [comment]
Y si en el controlador escribes:
```ruby
def hello
   render html: '<h1>Hola!</h1>'.html_safe
end
```

Te muestra el "Hola!" ??

**Comment by ranelson1** [comment]
Si lo muestra

**Comment by elramirezv** [comment]
@ranelson1  Si es que te funciona, entonces prueba comentando (o eliminando) las siguientes líneas del archivo `app/views/layouts/application.html.erb`:

```ruby
<%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
```
Te muestra la vista ahora ? 

Si es que eso te funciona, entonces podría ser que el nombre de tus carpetas esté afectando al path de referencia a la aplicación. Prueba con que el nombre de tus carpetas no tengan espacios dentro de ellas. Por ejemplo, si tienes: `/IIC 2143 [INGENIERÍA DE SOFTWARE]/`, que sea: `/IIC-2143-[INGENIERÍA-DE-SOFTWARE]/`.

Avísame si te funciona 😄 

**EDIT:** Para asegurarnos, sácale los tildes y el simbolo "º" al 9 también.

**Comment by ranelson1** [comment]
@elramirezv123 Muchisimas gracias!! era eso, el path de mi app, al final movi la app al desktop y se soluciono todo jajajaja

**Comment by elramirezv** [comment]
Buenísimo 😄 !
