### ISSUE TITLE
Orden del archivo final

### ISSUE THREAD

**Issue by furzuadr** [IIC2143-2020-1/proyecto#39]
Hola! Estoy teniendo un problema al escribir en el archivo final.
Mi programa corre, lee las instrucciones y escribe el archivo bien, pero no respeta el orden de las instrucciones. 
Tengo:
`pasajeros en cuarentena
habitantes en cuarentena`
Pero a veces lo imprime como si fuera:
`habitantes en cuarentena
pasajeros en cuarentena`
Será porque estoy corriendo las instrucciones con un send() dentro de un each? Es como si se corrieran en paralelo y la primera en terminar se imprimiera. Hay alguna forma de correr un array de instrucciones y que sólo se ejecute la siguiente al terminar la primera? Gracias!

**Comment by daleal** [comment]
Hola! La instrucción `send` no spawnea un thread para su ejecución (es decir, es una función como cualquier otra) y el each es equivalente a correr un `for` en Python (es decir, cada iteración va después de la siguiente), por lo que probablemente se debe a algún otro tipo de problema.
