### ISSUE TITLE
Error de instalación de Ubuntu en VirtualBox

### ISSUE THREAD

**Issue by isiguelfand** [IIC2143-2020-1/proyecto#4]
Hola!
Estoy intentando instalar Ubuntu en VirtualBox, pero siempre entre el paso 8 y 10 de la Wiki (entre "preparar para instalar Ubuntu" y "eliminar disco") la máquina virtual se queda pegada y/o el mouse deja de funcionar dentro de ella. Tengo porcentaje de la memoria de video asignada y además intenté aumentando el número de monitores CPU. La aceleración 3D está deshabilitada (estas fueron las soluciones propuestas que encontré). 
Mi sistema operativo es Mac. 
Gracias

**Comment by elramirezv** [comment]
Hola!

¿Por qué estás intentando usar Ubuntu si tienes macOs? Te recomendamos instalarlo directamente sobre tu sistema operativo, ya que Ruby se comporta bastante bien sobre macOs 😄

**Comment by isiguelfand** [comment]
Gracias! Lo tengo claro, ya tengo instalado ruby en macOs, pero quería aprovechar de hacerlo ahora para poder familiarizarme con Ubuntu, por que tengo entendido me será útil en el futuro y para otros ramos.

**Comment by daleal** [comment]
Hola! Me da la impresión de que tu error es extremadamente específico a tu máquina, por lo que es difícil que podamos ayudarte :disappointed:. Lo que a veces pasa es que hay algunas opciones en la instalación que no están bien soportadas por la máquina en que se instala (en este caso una máquina virtual) y la instalación se queda pegada (me ha pasado un par de veces), por lo que lo único que podría recomendarte hacer sería intentar hacer la instalación con distintas configuraciones (desacrivando instalación de drivers gráficos _third party_, por ejemplo). Ese tipo de problemas, en todo caso, en general se deben al instalador de ubuntu y no a problemas en la máquina.
