### ISSUE TITLE
Error sample_medium_log.txt

### ISSUE THREAD

**Issue by vicerc** [IIC2143-2020-1/proyecto#40]
Holaa, 
Estaba debbugeando mi archivo y me di cuenta que en el sample no sale como pasajero en cuarentena el Lic. Jaime Estévez cuando uno de sus viajes (id=30) fue hace 13 días, es decir, si debería estarlo.

**Comment by daleal** [comment]
Hola! Tienes toda la razón, no apliqué el filtro de tiempo en los viajes.

**El archivo de output del dataset mediano debería cambiar, los demás archivos no cambiaron**, por si acaso. Muchas gracias! :heart:

**Comment by vicerc** [comment]
De nada <3
