### ISSUE TITLE
duda output file tarea ruby

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2143-2020-1/proyecto#41]
hola da lo mismo si entre output de instrucción le agregue un espacio para que fuera más ordenado?
Por ejemplo 
*** COMIENZO PASAJEROS EN CUARENTENA ***
*** FIN PASAJEROS EN CUARENTENA ***

*** COMIENZO HABITANTES EN CUARENTENA ***
*** FIN HABITANTES EN CUARENTENA ***
Omitiendo en este ejemplo los resultados de pasajeros y habitantes en cuarentena

Pregunto por si van a corregir la tarea de manera automática y tiene que ser exacto
Gracias de antemano

**Comment by daleal** [comment]
Hola! Por favor no agregues el espacio. Gracias!

**Comment by JuaniAndres** [comment]
yap gracias

**Comment by vicerc** [comment]
Holaa, ¿importa si los id que aparecen en el output file no aparecen en el mismo orden que en los samples, pero son los mismos a fin de cuentas?

**Comment by daleal** [comment]
Hola! No podemos obligarlos a expresar el output en el mismo orden en que lo expresamos nosotros, pero agradeceríamos mucho que lo hicieran, ya que las tareas serán revisadas en masa y si tu output es distinto al esperado habrá un resultado que parecerá erróneo, cosa que nos tomará mucho más tiempo. Lo que puedes hacer es obtener tu solución, ordenar ese arreglo por `id` y luego _loggearlo_, para que quede con el mismo orden que nosotros vamos a usar.

**Comment by vicerc** [comment]
Ok, lo haree
