### ISSUE TITLE
Error incluyendo gem 'pg' en gemfile

### ISSUE THREAD

**Issue by jfpena1** [IIC2143-2020-1/proyecto#42]
Hola al tratar de incluir la gema me tira el siguiente error:
```
Fetching pg 1.2.3
Installing pg 1.2.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

Finalmente sugiere:
Make sure that `gem install pg -v '1.2.3' --source 'https://rubygems.org/'` succeeds before bundling.

Seguí los pasos que se indicaban en la clase y esto ocurrió. Tengo instalado rails en windox linux subsystem. 

Muchas gracias

**Comment by elramirezv** [comment]
Hola @jfpena1 !

Tienes instalado e inicializado PostgreSQL en tu computador?

**Comment by jfpena1** [comment]
Voy a tratar de hacerlo denuevo, pq parece que la instalación habia tenido un problema en el  programa de stackfile que se instala juto con postgres, gracias

**Comment by jfpena1** [comment]
Lo volví a instalar y sigue ocurriendo lo mismo, que podría hacer?

**Comment by meretamal** [comment]
Hola 😁 !!

Si es que ya tienes PostgreSQL instalado, es probable que te falten algunas dependencias de desarrollador.

Se que en Ubuntu se instala con `sudo apt-get install libpq-dev`, pero nunca he usado WLS por lo que no sabría decirte si te funcionaría. 

Si es que alguno con OSX tiene el mismo problema, se instala con `brew install postgresql`.
