### ISSUE TITLE
Inconsistencia versión de Ruby

### ISSUE THREAD

**Issue by benjastraub** [IIC2143-2020-1/proyecto#43]
Hola, 

instalé RVM para hacer un downgrade de la versión de ruby.

El problema es que al usar `rvm current` me retorna `ruby-2.6.5` pero si escribo `ruby -v` retorna `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]`

(Estoy usando bash en Manjaro XFCE)

**Comment by meretamal** [comment]
Hola, cuando corres `rvm list`, qué versiones te aparecen y cual te aparece que se usa por default?

**Comment by benjastraub** [comment]
Sólo me aparece la 2.6.5 y dice que es la default

```
=* ruby-2.6.5 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

```

**Comment by elramirezv** [comment]
Hola @benjastraub !

Quizás podría ser que la `2.7.0` la instalaste vía `rbenv`? Si ejecutas `rbenv versions` te funciona ?

**Comment by benjastraub** [comment]
@elramirezv123 lo había instalado con `pacman`. Al final lo desinstalé y lo borré del path. Ahora si me reconoce el 2.6.5

Muchas gracias!

**Comment by elramirezv** [comment]
👌👌
