### ISSUE TITLE
Problema para crear base de datos en pgadmin4

### ISSUE THREAD

**Issue by pedrobihan** [IIC2143-2020-1/proyecto#44]
En el video Rails: Modelo relacional, persistencias y formularios, en el minuto 28:20 el profesor, una vez dentro de pgadmin4, aprieta donde dice Servers y se le despliegan varias opciones, dentro de ellas la cual usa para crear la nueva base de datos. Yo aprieto donde dice Servers y no pasa nada, como se ve en la foto que subí. Alguna idea de como arreglarlo o una forma alternativa de hacer lo mismo?
gracias

![unnamed](https://user-images.githubusercontent.com/53802778/77709908-4d962e00-6fab-11ea-98d7-003374f9aa66.jpg)

**Comment by daleal** [comment]
Hola! No podría decirte cómo usar `pgadmin4` debido a que nunca lo he usado, pero según leí en internet, debes crear un _server_ antes de poder acceder a uno. [Aquí hay una guía](https://docs.bitnami.com/installer/apps/canvaslms/administration/configure-pgadmin/) de cómo setear la herramienta (me imagino que puedes partir desde el paso que dice `Launch pgAdmin 4.`).
