### ISSUE TITLE
CLase miercoles 25 (profesor Navon)

### ISSUE THREAD

**Issue by jalliende** [IIC2143-2020-1/proyecto#45]
Donde esta el vídeo de la clase? no la encuentro en canvas. gracias.

**Comment by daleal** [comment]
Hola! Como el profesor dijo en [este anuncio](https://cursos.canvas.uc.cl/courses/7171/discussion_topics/47296), no hubo clases el miércoles 25.

**Comment by jalliende** [comment]
Sisi leí el anuncio era solo que pensé que iba  subir el contenido antes, gracias.
