### ISSUE TITLE
Error fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by Juanvg213** [IIC2143-2020-1/proyecto#46]
Hola, después de crear la "app" usando rails con el comando:
>  rails new app --database=postgresql

inicio el servidor con:

> rails s

Y al momento de ingresar a localhost:3000 en el navegador, el siguiente error emerge:

> fe_sendauth: no password supplied

¿Alguna tip para resolver esto? (no logré encontrar una solución en google)

**Comment by meretamal** [comment]
Hola!! Puedes mandar una foto del archivo database.yml?

**Comment by Juanvg213** [comment]
![duda1](https://user-images.githubusercontent.com/53798632/77781791-f177ec00-7034-11ea-9356-c304b2999bea.png)
![duda2](https://user-images.githubusercontent.com/53798632/77781797-f341af80-7034-11ea-88aa-96d29454e409.png)

**Comment by meretamal** [comment]
En `development`, podrías intentar descomentar `username` y `password`, y escribir en username `postgres` y dejar la contraseña en blanco?

**Comment by Juanvg213** [comment]
Sigue saliendo el mismo error de antes.

**Comment by JuaniAndres** [comment]
Tengo el mismo problema. Trate de solucionarlo ayer y hoy con lo que encontré en Internet pero nada me funciona.

**Comment by meretamal** [comment]
Hola @JuaniAndres, qué sistema operativo usas?

**Comment by JuaniAndres** [comment]
hola @meretamal 
Windows 10

**Comment by meretamal** [comment]
Parece ser un problema bastante común en Windows en torno a la configuración de Postgres.

Puedes ir a **C:\Program Files\PostgreSQL\<versión>\data** y ver si tienes un archivo llamado **pg_hba.conf**?

**Comment by JuaniAndres** [comment]
si lo tengo

![Cap](https://user-images.githubusercontent.com/48482216/77828450-3dd92f80-70fa-11ea-9b2f-fcc38eab5da9.PNG)

**Comment by meretamal** [comment]
Dale, puedes abrir una consola de SQL y correr `\du`?

**Comment by JuaniAndres** [comment]
te refieres a psql? Asumiendo que si 
Es raro porque si pongo psql me pide una contraseña para usuario Juan Andres que supongo que fue auto generada y que creo no tengo. Igual me salto eso entrando como el usuario postgres y la super clave y obtengo esto de \du
![Cap](https://user-images.githubusercontent.com/48482216/77829028-0ec4bd00-70fe-11ea-92ee-1bf87c9db245.PNG)

**Comment by meretamal** [comment]
Pasan distintas cosas:

1. En Postgres existen distintos roles, los cuales tienen distintos permisos.
2. Si en el archivo **database.yml**, en `development` dejas `usarname` y `password` en blanco (al igual que en `test`),  se asumirá que quieres ingresar con un rol del mismo nombre que tu usuario de tu pc, el cual tendría todos los atributos necesarios para trabajar sin problemas en tu proyecto. Parece que en Windows no se crea este rol junto con la instalación de Postgres, lo que explica por qué levantaría el error cuando no escribes nada en estos campos, ya que el rol de por si no existe.
3. Una solución podría ser utilizar el rol `postgres`, el cual no tiene contraseña (y también agregar estos campos en `test`).
4. En el caso de Windows, en la configuración de Postgres viene definido el método **md5** como el método de autenticación de roles, el cual te obliga ingresar una contraseña, por lo que, como el rol `postgres` no tiene, te lanza ese error.

Posibles soluciones:

1. Cambiar **md5** a **trust**, reiniciar tu _server_ de postgres y utilizar el rol `postgres`.
2. Crear un _superuser_, asignarle una contraseña y utilizar estos datos en `development` y `test`  en **database.yml**

Dado que vas a trabajar con más gente, para facilitar el trabajo, te recomiendo la primera opción.

Dime si te funciona 😁.

EDIT: En el caso de que al instalar Postgres se les haya pedido asignarle una contraseña, si es que la ponen en **database.yml** (con usuario `postgres`), deberían poder hacer el _set  up_ de la base de datos sin problemas, sin embargo, para evitar conflictos con su grupo, les recomiendo usar [variables de entorno](https://launchschool.com/blog/managing-environment-configuration-variables-in-rails) para no tener que escribir explícitamente estos datos en el archivo.

**Comment by JuaniAndres** [comment]
yap voy a intentar la primera en un rato más pero que lineas cambio a trust o cambio todas?

**Comment by meretamal** [comment]
Según lo que he visto, por lo general tienen todas en `trust`, pero ve si te basta con IPv6 y sino con IPv4.

Te dejo un link donde puedes ver los distintos tipos de autenticación, si es que te interesa aprender un poco de esto (https://www.postgresql.org/docs/9.1/auth-methods.html#AUTH-PASSWORD).

**Comment by JuaniAndres** [comment]
Me funciono muchas gracias @meretamal  
Por si alguno esta en la misma lo que hice es:
1. Modificar el **pg_hba.conf** cambiando la linea del IPv6 de `md5` a `trust`
2. En la **database.yml** poner `username: postgres` y `password:`  a la parte development y test

**Comment by jalliende** [comment]
Me pasaba el mismo error, gracias a los que respondieron las dudas

**Comment by perezpefaur** [comment]
Hola! No entendi muy bien como solucionar el problema

**Comment by perezpefaur** [comment]
Hola estuve investigando un poco y cambiar de md5 a trust parece que es inseguro (obviamente da lo mismo en este caso ya que no es un proyecto que requiera seguridad), la verdad que nose cual es la razón, pero bueno. Entonces  lo que yo hice que me parece más lógico es setear test y development asi:
development:
  adapter: postgresql
  encoding: unicode
  database: app_development
  pool: 5
  username: postgres
  password: TUCLAVE
  host: localhost
  port: 5432 
test:
  adapter: postgresql
  encoding: unicode
  database: app_test
  pool: 5
  username: postgres
  password: TUCLAVE
  host: localhost
  port: 5432

**Comment by perezpefaur** [comment]
La verdad que nose si lo de arriba tendrá alguna implicancia práctica y termine siendo peor, pero para lo que es crear db me funciono. Agradeceria mucho si alguien puede comentar sobre la validez  de esta solución.

**Comment by JuaniAndres** [comment]
Hola según lo que investigue yo cuando estaba tratando de solucionarlo era que también era inseguro hacer lo del trust sin embargo como vamos a estar trabajando en equipo y para que les funcione a todos tengo entendido que todos tendrían que tener la misma clave cuando instalaron postgres para que les funcione con el archivo que escribiste arriba o cada uno editar su archivo y pusiera su propia clave que no se si traería problemas más adelante. La otra opción que creo que funcionaria es que todo el equipo creara un usuario nuevo en postgres con el mismo nombre y la misma clave en ese caso supongo que funcionaria un mismo archivo para todo el equipo con los datos de ese nuevo usuario.
Igual no estoy tan seguro de lo que dije a lo mejor @meretamal te puede responder mejor

**Comment by meretamal** [comment]
Hola :grin: !! si efectivamente quieren utilizar otro rol con contraseña en su configuración, les recomiendo no dejar sus credenciales explícitas en **database.yml**. Para esto pueden usar **variables de entorno**. De esta manera puede facilitarse lo que explicaba @JuaniAndres.

Acá les dejo un [link](https://launchschool.com/blog/managing-environment-configuration-variables-in-rails) donde pueden ver como hacerlo. Yo, en lo peronsal, he usado _dotenv_.

**Comment by perezpefaur** [comment]
Ahi lo maneje con dotenv! Muchisimas gracias!

**Comment by ranelson1** [comment]
Hola! Moises, @meretamal 

yo todavia no puedo solucionar el error, probe tratando de cambiar los permisos a trust y no me funciono. Luego, reverti todo y lo deje en md5.

probe dejando 
username: vacio
password: vacio
![image](https://user-images.githubusercontent.com/53798928/78409286-9ec3a480-75df-11ea-8248-adf68bc9ffe6.png)

username: postgres
password: 
![image](https://user-images.githubusercontent.com/53798928/78409350-d9c5d800-75df-11ea-8739-e467dcba49ae.png)

username: postgres
password ***miclave***
![image](https://user-images.githubusercontent.com/53798928/78409414-feba4b00-75df-11ea-963c-ce8320fe8bf4.png)
