### ISSUE TITLE
[Tarea 0] Orden de datos en funciones

### ISSUE THREAD

**Issue by FeBalla** [IIC2143-2020-1/proyecto#48]
Hola, quería saber si no hay problema con que los resultados de una función estén correctos, pero en diferente orden con respecto a los ejemplos entregados. 
Por ejemplo, si se hiciera la consulta **A**, en el output de ejemplo para esa consulta la respuesta del ejemplo que subieron es:

- a
- b
- c

Sin embargo, yo tengo:

- b
- c
- a
¡Gracias!

**Comment by elramirezv** [comment]
Hola @FeBalla !

La respuesta está en #41. Ideal que sea el mismo orden 😄
