### ISSUE TITLE
Configurar clave db en el proyecto

### ISSUE THREAD

**Issue by benjastraub** [IIC2143-2020-1/proyecto#49]
El profesor muestra en uno de los videos que cuando configura `config/database.yml` para poder utilizar psql que se debe incluir el parámetro `password: <contraseñapsql>`.

¿Hay alguna forma de configurar esto sin tener que escribir la contraseña en el archivo? Siento que no es una buena práctica que las contraseñas queden a la vista :eyes:

**Comment by meretamal** [comment]
Hola!! Si lo que quieres es definir un usuario/rol especifico de postgres en `database.yml`, para no tener que escribir de manera textual la contraseña puedes utilizar variables de entorno.

Acá te dejo un link donde muestran distintas maneras de implementarlas. Yo en lo personal he usado `dotenv`. (https://launchschool.com/blog/managing-environment-configuration-variables-in-rails).
