### ISSUE TITLE
Problemas al cargar archivos de la ayudantia

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2143-2020-1/proyecto#5]
Al tratar de correr el codigo de archivo de la ayudantia desde mi mac (por si es relevante me arroja el siguiente error). Estoy corriendo el archivo directamente desde la carpeta de ayudantias clonada de git

<img width="952" alt="Captura de pantalla 2020-03-19 a la(s) 01 21 04" src="https://user-images.githubusercontent.com/53799932/77031301-edd2ce00-697f-11ea-9ef8-c6454e34d24b.png">

A que se debe esto?

**Comment by jmndoza** [comment]
Hola @Alonsinho1, según yo, tienes un problema de rutas relativas, tu terminal esta situado en tareas alonso, y debería estar en ayudantias/ruby, y ahi correr el programa. 
El archivo .rb busca files/read.txt

**Comment by Alonsinho1** [comment]
efectivamente. habia abierto el archivo de la ayudantia mientras estaba trabajando en la carpeta de tareas de ruby para probar. Muchas gracias
