### ISSUE TITLE
Problema de instalación rails y rvm en ios

### ISSUE THREAD

**Issue by bgonzlez** [IIC2143-2020-1/proyecto#50]
Hola, he intentado de todo para instalar rvm así que simplemente me rendí, sin embargo adjuntaré lo que dice mi terminal. Lo mismo con rails, aparece que no existe. aquí está:
![Captura de Pantalla 2020-03-28 a la(s) 00 01 23](https://user-images.githubusercontent.com/53842152/77813442-6ffd7980-7087-11ea-94b5-58acda48b6d2.png)
![Captura de Pantalla 2020-03-28 a la(s) 00 02 17](https://user-images.githubusercontent.com/53842152/77813459-94f1ec80-7087-11ea-943e-74c5abf7650f.png)

**Comment by nabenitez** [comment]
Hola!,

Para rails prueba con la sugerencia que te da la consola, utiliza el comando sudo.
`sudo gem install rails -v 5.2`

Para rvm prueba primero corriendo:
`gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB`

Y después:
`\curl -sSL https://get.rvm.io | bash -s stable --ruby`

Avísame cómo te va!

**Comment by bgonzlez** [comment]
Hola, si las dos cosas ya las probé varias veces días atrás, este es el resultado
![Captura de Pantalla 2020-03-28 a la(s) 12 21 58](https://user-images.githubusercontent.com/53842152/77826544-d964a300-70ee-11ea-8e05-8d1b8d2dfac5.png)
![Captura de Pantalla 2020-03-28 a la(s) 12 20 56](https://user-images.githubusercontent.com/53842152/77826550-de295700-70ee-11ea-9d72-3cc13f031694.png)

**Comment by jmndoza** [comment]
Hola @bgonzlez, 
Si lo instalaste con rvm, intenta crear un gemset e instalas rails ahi, 
https://rvm.io/gemsets/basics

para el uso de gemset:
https://rvm.io/gemsets/using

Espero te sirva...

**Comment by nabenitez** [comment]
Finalmente, se desinstalo Ruby 2.7. Y luego se instaló todo siguiendo:
https://gorails.com/setup/osx/10.15-catalina
**Ruby 2.6.5**
**Rails 5.2.4.1**
