### ISSUE TITLE
rails new no me crea todos los archivos

### ISSUE THREAD

**Issue by bahidalgo** [IIC2143-2020-1/proyecto#51]
Hola, tengo un problema al utilizar "_rails new app_", pues solo me crea lo que indica la imagen (y según veo, debiese crear una gran cantidad de carpetas). Intenté reinstalando rails 5.2 pero el problema persiste.

![imagen_Error](https://user-images.githubusercontent.com/48327186/77824622-d663b580-70e2-11ea-9eef-34df4f05af97.png)

**Comment by elramirezv** [comment]
Hola @bahidalgo !

Podría ser que `Rails` no se haya instalado correctamente, si intentas desintalando e instalando de nuevo?

**Comment by bahidalgo** [comment]
Lo he reinstalado varias veces. De hecho, al pedir la versión, me arroja correctamente rails 5.2 (al estar instalado) y error en caso de estar desinstalado.
Usé "gem uninstall rails" y luego "gem uninstall railties". Lo acabo de volver a reinstalar por n-ésima vez y nada. Auxilio.

![fotoerro](https://user-images.githubusercontent.com/48327186/77828078-43ce1100-70f8-11ea-876d-67a7d0588408.png)

**Comment by meretamal** [comment]
Hola!! Puedes correr `git --version` para asegurarte que tienes git instalado?

**Comment by bahidalgo** [comment]
Eso era! PowerShell no reconocía git, pero logré usarlo en el cmd. Mil gracias!

**Comment by daleal** [comment]
Para aclarar lo que sucedió aquí por si a alguien más le pasa lo mismo, el comando `rails new` necesita `git` para poder ejecutarse correctamente. Si no encuentra `git`, genera algunos archivos y luego falla.
