### ISSUE TITLE
[Tarea 0] Duda modo de escritura output.txt

### ISSUE THREAD

**Issue by Tito0906** [IIC2143-2020-1/proyecto#52]
Holaa, tengo una duda sobre cómo crear el archivo final. En específico, no estoy seguro de qué modo ocupar para escribir el resultado en output.txt. Si ocupo el modo "w", crea pero reemplaza todo el archivo si ya existia. Si uso "a" se crea el archivo pero si ya existe, entonces escribe el resultado continuando el archivo. Quería saber si podemos asumir que el nombre de los archivos output.txt será diferente o si tenemos que considerar que el archivo se llamará igual y que con cada corrida del programa debe eliminar el contenido del archivo anterior y escribir el nuevo.

**Comment by daleal** [comment]
Hola! Puedes elegir cualquiera de los dos modos de escritura.

**Comment by Tito0906** [comment]
Muchas gracias!
