### ISSUE TITLE
Inconsistencia entre instrucciones y programa

### ISSUE THREAD

**Issue by nicoguz** [IIC2143-2020-1/proyecto#54]
Hola!!
Estoy teniendo un problema donde mi programa lee cada linea del archivo de instrucciones pero cuando quiero comparar las lineas me dice que son distintas excepto por la última. Ya comprobé que son iguales a las que escribí yo mismo en un archivo txt y aun así me dice que son distintas cuando las comparo en un 'if'. También probé agregando los \n y espacios al inicio y/o final pero sigue siendo distinto. Ayuda por favor!!!

**Comment by elramirezv** [comment]
Hola @nicoguz !

> Estoy teniendo un problema donde mi programa lee cada linea del archivo de instrucciones pero cuando quiero comparar las lineas me dice que son **distintas excepto por la última**.

Por última te refieres a la última instrucción o última letra de la instrucción? ¿Cómo estás leyendo el archivo? Puedes subir un pequeño ejemplo?

Quizás si le aplicas `.strip` para asegurarte de "limpiar" el string 😄

**Comment by nicoguz** [comment]
Es la última instrucción, pero aplique el `.strip` y me funcionó perfect. Graciass!!!
