### ISSUE TITLE
contenidos .zip Tarea ruby

### ISSUE THREAD

**Issue by jfpena1** [IIC2143-2020-1/proyecto#55]
En la entrega sale "subir un archivo .zip sin archivos .csv no txt", nose si es un typo y debiese decir "o txt" o efectivamente los txt si hay que subirlos.

Muchas gracias

**Comment by elramirezv** [comment]
Hola @jfpena1 !

Solo debes subir tu programa 😄, no tienes que subir `.csv` ni `.txt`
