### ISSUE TITLE
Maquina virtual

### ISSUE THREAD

**Issue by Deleon20** [IIC2143-2020-1/proyecto#56]
Hola! En mi grupo todos tenemos computadores que operan Windows y hemos tenido algunos problemas con rails. Y en la ayudantia nos dijeron que era mejor correrlo en una maquina virual como la que aparece en la wiki pero que tambien era complicado usarla e inestable. Cual seria entonces la mejor opcion para programar en rails, sin deshacernos de windows claro?

**Comment by elramirezv** [comment]
Hola @Deleon20 !

Yo personalmente recomiendo hacer una partición e instalar Ubuntu, pero si no quieres hacer algo tan """drástico""", podrías probar instalando Ruby y Rails con la Windows PowerShell, y sino, con el Linux Subsystem :+1:
