### ISSUE TITLE
Ayudantía 2

### ISSUE THREAD

**Issue by castrillini** [IIC2143-2020-1/proyecto#57]
Hola, disculpen
¿Dónde y cuándo subirán el video de la ayudantía 2 realizada el viernes 27?

**Comment by meretamal** [comment]
Hola 😁 !! Acá puedes encontrar las ayudantías que se han realizado hasta el momento (https://www.youtube.com/playlist?list=PLho7v0gqei1CklmTF5gGy02VxMUN-clnJ).
