### ISSUE TITLE
Tarea Ruby: Instrucciones.txt

### ISSUE THREAD

**Issue by TrigalJeruti** [IIC2143-2020-1/proyecto#59]
Hola! En la tarea se dice que las instrucciones.txt estarán en la misma carpeta que los archivos csv pero luego en el ejemplo sale que instrucciones.txt esta afuera junto al main.rb. Me gustaría saber en que lugar efectivamente estará instrucciones.txt
De antemano muchas gracias.

**Comment by elramirezv** [comment]
Hola @TrigalJeruti !

Estará junto al `main.rb` :smile:
