### ISSUE TITLE
Duda Versión de Ruby

### ISSUE THREAD

**Issue by matiasmasjuan** [IIC2143-2020-1/proyecto#6]
Hola!

En los anuncios de la **Tarea Ruby** señalaron que van a utilizar la versión de ruby **2.7.0** para corregirla. Sin embargo, el profesor en clases (junto con las slides) nos dijo que utilizaramos la versión **2.6.x**. ¿Cuál debemos utilizar?

**Comment by elramirezv** [comment]
Hola @matiasmasjuan!

Dado que la corrección la hacemos los ayudantes, utiliza la versión **2.7.0** 😄

**Comment by matiasmasjuan** [comment]
Gracias!

**Comment by daleal** [comment]
Hola! Para cualquiera leyendo esta issue, la/lo invito a leer la issue #8.
