### ISSUE TITLE
Cómo acceder a variable de clase estática desde otra clase

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2143-2020-1/proyecto#61]
Hola! Tengo un problema con la tarea. Cambiando los nombres, mi código es

`class Fruta`
`@@frutas = Array.new()  #donde guardo todas las instancias de Fruta`

Y quiero poder hacer, en otra parte del código

`Fruta.frutas`

Gracias!

**Comment by elramirezv** [comment]
Hola @ChayoPerez !

En el ejemplo de [clases](https://github.com/daleal/ruby-examples/blob/master/09_class.rb) del repositorio [`ruby_examples`](https://github.com/daleal/ruby-examples) de @daleal, se muestra como escribir los atributos de una clase correctamente :smile:.

Y en #33 se menciona algo que te puede servir 👍
