### ISSUE TITLE
Tarea 0 output file

### ISSUE THREAD

**Issue by Ignaciomendezp** [IIC2143-2020-1/proyecto#62]
Hola! Tenía una duda de la tarea. Se nos dice que nuestro output file tiene que tener el nombre que se nos entrega en el tercer argv. Cuando se nos entrega el nombre va a incluir el .txt? o nosotros tenemos que agregarle el .txt al nombre que nos den? Gracias

**Comment by elramirezv** [comment]
Hola @Ignaciomendezp !

Tendrá el .txt
