### ISSUE TITLE
variable no reconocida en metodo

### ISSUE THREAD

**Issue by mpsubiabre** [IIC2143-2020-1/proyecto#66]
Hola, 
Tengo el método personas_en_cuarentena() que no recibe ningún argumento, sin embargo dentro de este método quiero abrir el archivo de instrucciones.txt, el nombre de este archivo se guarda en una variable utilizando output = ARGV[2] (es ingresado de la consola). Comprobé (con puts) que la variable tenga el string correcto(instructions.txt), por lo que en ese sentido esta todo en orden. Sin embargo dentro del método no reconoce esta variable. Esta variable es definida antes de la definición del método y antes de llamar al método. Como puedo arreglar esto?

Algo asi sucede:

def pasajeros_en_cuarentena()
  File.open("#{output}", "w") do |f|
     f.puts "a"
  end
end
Es el siguiente error:
main.rb:89:in `pasajeros_en_cuarentena': undefined local variable or method `output' for main:Object (NameError)

Muchas gracias.

**Comment by elramirezv** [comment]
Hola @mpsubiabre !

Esto te sucede dentro de una clase? Si ese es el caso, entonces agrégale un "@" a la variable output y así podrás acceder a ella desde cualquier método.

Si es una función "suelta", entonces tienes que pasársela como parámetro.

**Comment by mpsubiabre** [comment]
Si es una función "suelta", así como me indicas si funciona, pero puedo editar el archivo instrucciones.txt y hacer que reciba parámetro? Es decir, para revisar la tarea de correrá el archivo que suba yo de instrucciones ? O será exactamente igual indicado? y con eso puedo manejarlo como quiera? Porque en el enunciado los métodos no reciben parámetros

**Comment by elramirezv** [comment]
El archivo `instrucciones.txt` y como manejes tus funciones, son cosas distintas. Puedes hacer lo que quieras con tus funciones, por eso la modelación es libre. Sin embargo,  el archivo de instrucciones **NO** lo debes editar, ya que utilizaremos el mismo para todos.

**Comment by mpsubiabre** [comment]
Perfecto, muchas gracias ! Veré cómo solucionarlo
