### ISSUE TITLE
Mensaje de rails (SIG... not implemented)

### ISSUE THREAD

**Issue by Tito0906** [IIC2143-2020-1/proyecto#67]
Holaa, tenía una duda sobre el significado y posibles consecuencias de un mensaje que me aparece en rails (tengo windows). El mensaje es el siguiente:

*** SIGUSR2 not implemented, signal based restart unavailable! 
*** SIGUSR1 not implemented, signal based restart unavailable! 
*** SIGHUP not implemented, signal based logs reopening unavailable!

La verdad es que se me había olvidado preguntar antes, ya que descargué rails hace tiempo y he podido hacer todo lo de las clases sin problemas, pero quería saber si este mensaje podía ser importante a futuro.

**Comment by daleal** [comment]
Hola! Esos mensajes ocurren debido a que en Windows no existe `fork`. La implicancia que pueden tener es que puede que no seas capaz de reiniciar el servidor con una señal (sin embargo, siempre puedes detener el servidor y volver a iniciarlo). No hay realmente forma de resolverlo, ya que se debe al sistema operativo, pero no debería significar ningún problema.
