### ISSUE TITLE
Problema para crear base de datos desde WSL

### ISSUE THREAD

**Issue by naviera** [IIC2143-2020-1/proyecto#68]
Instalé Ruby 2.6.5 y Rails 5.2.4.2 en WSL según la guía en https://gorails.com/setup/windows/10, y PostgreSQL 12.2 en Windows también según las instrucciones de la guía. Luego seguí las instrucciones de la clase (video) para configurar rails con postgres y al llegar al paso del comando "rake db: migrate" me tira el siguiente error:
![image](https://user-images.githubusercontent.com/31016474/78277344-bc631200-74ea-11ea-9a1f-ec0e0d825238.png)

Si sigo las instrucciones de la guía, creando la base de datos con "rake db:create" aparece el mismo error.

**Comment by valerojasm** [comment]
Hola! 

Esto significa que postgres no está corriendo. En general esto se puede arreglar [así](https://askubuntu.com/questions/1206416/how-to-start-postgresql), iniciándolo manualmente - hay algunas personas a las que les pasa. Avísame si te funciona y si no, para ver qué más hacer para que podamos arreglarlo.

Saludos!

**Comment by naviera** [comment]
Hola! Dice que no encuentra el comando pg_ctl

**Comment by valerojasm** [comment]
Intenta con [esta otra opción](https://dba.stackexchange.com/questions/156717/command-not-found-pg-ctl-on-ubuntu) para inciar el servidor y cuéntame cómo te va.
