### ISSUE TITLE
Problemas con html

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2143-2020-1/proyecto#69]
Hola! estoy tratando de definir el siguiente codigo y estoy teniendo problema en como se esta leyendo cada vez que se termina con "%>" aqui tengo detalles 

![image](https://user-images.githubusercontent.com/53799932/78318795-0f18ea00-753c-11ea-8873-8c5c82f53693.png)

![image](https://user-images.githubusercontent.com/53799932/78318811-18a25200-753c-11ea-8dca-48d8420dd414.png)

**Comment by elramirezv** [comment]
Hola @Alonsinho1 !

En el cierre del tag `<table>` tienes un` \ `en vez de un `/`. Debería ser `</table>`. 

Recomiendo una extensión de VS Code que se llama: [Auto Close Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag) para automatizar el cierre y evitar estos problema  😄
