### ISSUE TITLE
Problema al iniciar la aplicacion

### ISSUE THREAD

**Issue by camaruri** [IIC2143-2020-1/proyecto#70]
Tengo problemas al crear la aplicación:
vi que estaba instalado todo lo que necesito y tengo rails 5.2.4.2, tengo ruby 2.6.3 y postgresql 12.2
pero cuando parto la aplicación con rails _5.2.4.2_ new App -d postgresql
empieza pero después me tira una error:
An error occurred while installing bindex (0.8.1), and Bundler cannot
continue.
Make sure that `gem install bindex -v '0.8.1' --source 'https://rubygems.org/'`
succeeds before bundling.

Me dijieron que se arreglaba haciendo brew install postgresql denuevo para las depencdencias del desarrollador, y despues hacer bundle install y me tira el mismo error.

Ademas si hago rails s, me tira el siguiente error:
Could not find gem 'pg (>= 0.18, < 2.0)' in any of the gem sources listed in your Gemfile.

He buscado harto y no he podido arreglarlo.
Gracias

**Comment by daleal** [comment]
Intentaste corriendo el comando `gem install bindex -v '0.8.1' --source 'https://rubygems.org/'` antes de ejecutar `bundle install`?
En cuanto al error al ejecutar `rails s`, probablemente se debe a que el `bundler` no logró instalar las dependencias, por lo que `pg` no se encuentra en tu máquina.
