### ISSUE TITLE
Error: Postgresql no puede conectarse al servidor 

### ISSUE THREAD

**Issue by mpbascunan** [IIC2143-2020-1/proyecto#71]
Hola, cuando creo la app con rails y luego pongo rails server, resulta que al abrir localhost:3000 aparece:
could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Busqué en google cómo resolverlo pero ninguna de las soluciones que se proponen me ha funcionado.

**Comment by daleal** [comment]
Hola! Creo que hay dos posibles problemas.

1. Tu computador no tiene `PostgreSQL` corriendo, por lo que no puedes conectarte.
2. Tu computador si tiene `PostgreSQL` corriendo, pero no está corriendo en el puerto `5432`.

Yo me aseguraría primero de que efectivamente estás corriendo el programa. Si es así, tendrías que revisar en qué puerto está corriendo. En la issue #68 alguien tuvo un problema que probablemente sea por la misma razón que tu problema y se dieron un par de posibles soluciones. Te recomiendo leerlas!

**Comment by Juanvg213** [comment]
Hola tengo el mismo problema y PostgreSQL si esta corriendo en mi computador y el port si es 5432 y aún así sigue saliendo el mismo error. ¿Alguna ayuda de que tengo debo hacer?
![image](https://user-images.githubusercontent.com/53798632/78598793-f2233600-781d-11ea-85fc-4407ac8b022e.png)
![image](https://user-images.githubusercontent.com/53798632/78598815-fa7b7100-781d-11ea-87eb-589eddde5830.png)

**Comment by mpbascunan** [comment]
Me aparece lo mismo que a @Juanvg213

**Comment by elramirezv** [comment]
Hola @mpbascunan , @Juanvg213 !

Encontré este [link de StackOverflow](https://stackoverflow.com/questions/55434576/cant-connect-to-the-server-error-var-run-postgresql-s-pgsql-5432) y esta [issue](https://github.com/microsoft/WSL/issues/921) que quizás puedan servir para entender qué es lo que está pasando.

Al parecer cuando inician el servidor de Postgres, por alguna extraña razón no se les está creando el `/var/run/postgresql/.s.PGSQL.5432`, quizás se les está creando en otra parte? Si el error persiste, yo me inclinaría a instalar el [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) o derechamente a hacer una partición :smile:

**Comment by mpbascunan** [comment]
graciaas
