### ISSUE TITLE
Fecha Entrega 1 Proyecto

### ISSUE THREAD

**Issue by amaiajuanchuto** [IIC2143-2020-1/proyecto#73]
Hola, recién me di cuenta de que el viernes y sábado es feriado por semana santa, por lo que quería saber si existe la posibilidad de que la entrega se mueva para el día domingo o lunes para poder aprovechare esos días y pasarlos en familia.

Muchas gracias y quedo atenta a la respuesta! :smile:

**Comment by daleal** [comment]
#76 :heart:
