### ISSUE TITLE
Heroku en el proyecto

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2143-2020-1/proyecto#74]
Hola! el proyecto hay que subirlo a un Heroku dado por la universidad o puede ser a cualquiera? Gracias

**Comment by daleal** [comment]
Hola! Puede ser cualquiera. Es importante que dejen el link en su `README` para que el ayudante sea capaz de encontrarlo para corregirlo!

**Comment by DiegoEmilio01** [comment]
Tengo una duda de el formato de entrega. Lo que pasa es que logramos subir la app a heroku pero desde un repo exclusivo en github para ella. Los archivos de la app los subiremos al repo de entrega pero este repo contiene mas carpetas y documentos ¿La app en heroku debe ser literal la que entregamos o podemos tenerla en un repo aparte y entregar los archivos (que se pueden testear localmente) al repo de entrega? Esto para ser mas ordenados y separar las entregas del ambiente de desarrollo y sus respectivas branches.

**Comment by daleal** [comment]
Hola! Debe ser del repositorio que les entregamos. Deben ser capaces de hacer `git clone` del repo del curso y luego _deployear_ esos archivos a Heroku.

**Comment by DiegoEmilio01** [comment]
Y algun consejo para hacer eso? Lo que se me ocurre es subir a github desde la carpeta de la entrega y subir a heroku desde la carpeta de la app (el heroku create). Porque cuando intente subir algo del estilo repo/test_app/* me dio errores.

**Comment by DiegoEmilio01** [comment]
Y lo otro, debemos entregar una app que ya sea la definitiva sobre la cual trabajaremos o simplemente una app donde aplicamos lo visto en clases?

**Comment by daleal** [comment]
Te recomiendo tener todo en la raíz de tu repositorio, y los documentos que son específicos de la entrega los puedes dejar en una carpeta `docs` también en la raíz de tu repositorio. Con respecto a lo segundo, deben entregar una app sobre la que vayan a empezar a trabajar en el Sprint 1.

**Comment by jmndoza** [comment]
<img width="761" alt="Captura de Pantalla 2020-04-07 a la(s) 18 49 25" src="https://user-images.githubusercontent.com/24240983/78733516-ae125d00-7913-11ea-86ed-4baa31c3ceee.png">
Es posible que puedan habilitar esto? y así subir directamente desde el repo de la entrega? @daleal

**Comment by daleal** [comment]
No es necesario usar _Heroku Dashboard_. Para hacer _deploy_ de su app, espero que sigan [este flujo](https://devcenter.heroku.com/articles/getting-started-with-rails5#deploy-your-application-to-heroku).

**Comment by raimundoloeser** [comment]
Hola, nosotros seguimos el flujo y llegamos a obtener nuestro link de la pagina. Ahora tenemos una duda, como tenemos acceso todos a la app web que se genero? explicandome mejor, mi compañero corre el codigo heroku open pero nosotros no podemos ya que el proceso lo hizo el (con su cuenta de heroku) nose si me eplico

**Comment by daleal** [comment]
Lo primero que debe hacer su compañero que creó la app de Heroku es hacerlos colaboradores a través del _dashboard_ de Heroku. Luego, una vez que tienen instalado [el CLI de Heroku](https://devcenter.heroku.com/articles/heroku-cli), ejecutan `heroku login -i` e introducen sus datos de Heroku. Finalmente, con la consola en su repositorio, ejecutan `heroku git:remote -a <appname>`, donde `<appname>` corresponde al nombre de la aplicación en Heroku. Una vez hecho eso, todos pueden ejecutar los comandos de Heroku o hacer _deploys_.

**Comment by Dnpoblete** [comment]
Hola @daleal , tengo un problema y quería saber si me puedes ayudar, hice lo que comentaste pero me sale el siguiente error :

![image](https://user-images.githubusercontent.com/42362982/78952109-6b32bf80-7aa2-11ea-9776-9db6e2f7d3d0.png)

Y cuando hago pull me dice que no hay cambios.

Gracias y quedo atenta a la respuesta 😄

**Comment by daleal** [comment]
Hola! La verdad es que nunca me he enfrentado a esa situación, pero [aquí](https://devcenter.heroku.com/articles/collaborating) hay una guía de Heroku sobre colaboración en equipo. Me parece que al final de la guía habla sobre algo similar a lo que te ocurre a ti.

**Comment by martinnik10** [comment]
Hola! Segui los pasos para deployear la app a heroku, y se supone que deberia fucnionar, pero cuando entro en heroku y abro la app no funciona y me aparece esto.
![Captura](https://user-images.githubusercontent.com/53874423/78957720-22840200-7ab4-11ea-9488-5cead634c57a.JPG)
Gracias!

**Comment by constanzacontreras** [comment]
martinnik10, le pusiste ruta a la pagina? quizás sea eso el "/ruta"

**Comment by martinnik10** [comment]
Era eso! gracias

**Comment by daleal** [comment]
Dado que el problema original parece haber sido resuelto, cierro esta issue.
