### ISSUE TITLE
Problema crear base de datos para app

### ISSUE THREAD

**Issue by Pdesolmi** [IIC2143-2020-1/proyecto#77]
Hola estmos siguiendo los pasos de la ayudantía, y cuando corremos el comando rails db:create nos sale el siguiente error, estamos siguiendo todos los pasos del ayudante
![recorte error crear base de datos](https://user-images.githubusercontent.com/53836282/78722263-1dc61f00-78f7-11ea-977e-c9d0b6913bc5.PNG)

**Comment by daleal** [comment]
#46
