### ISSUE TITLE
No logro instalar la gema pg

### ISSUE THREAD

**Issue by fsmc** [IIC2143-2020-1/proyecto#78]
Hola! Al hacer lo mismo de la ayudantia creando mi app me sale que le gema gp 1.2.3 no puede instalarse, ya que no existe gp_config. Sin embargo, yo me descargue postgres e instale en mi computador (tengo mac), pero es como si no me reconociera que lo tuviera instalado. Por otra parte, intento instalarlo a través del terminal, poniendo: brew install postgresql. Para esto me intenta de instalar la dependencia de postgresql: krb5, pero esta última no logra instalarse y me sale esto:
<img width="567" alt="Captura de pantalla 2020-04-08 a las 15 20 25" src="https://user-images.githubusercontent.com/53883295/78819378-23c60980-79a4-11ea-8fac-b3481b41369e.png">

**Comment by fsmc** [comment]
Sería increible si me pudieran ayudar. Agradezco de antemano!

**Comment by shantifabri** [comment]
A  mi me paso algo parecido, también me daba un error con esa gema. 
Yo uso ubuntu, pero corrí este comando y me funcionó todo bien después:
`sudo apt-get install libpq-dev`

**Comment by fsmc** [comment]
Esque el problema mio se basa en que no puedo instalar krb5, y como esta es una dependencia de postgresql no me funciona

**Comment by daleal** [comment]
Hola! Tu problema no parece tener nada que ver con `krb5`. Más bien, aparentemente tu sistema operativo no puede usar `ld` para la instalación. Te recomiendo investigar a partir de ahí.
