### ISSUE TITLE
Cambio en Versión de Ruby recomendada

### ISSUE THREAD

**Issue by daleal** [IIC2143-2020-1/proyecto#8]
Hola a todos!

Como probablemente leyeron, nosotros hemos estado recomendando usar la versión de `ruby 2.7.0`. Debido a que aparentemente hay problemas entre algunas _gemas_ y `ruby 2.7.0`, **nuestra recomendación ahora es que usen `ruby2.6.x` para el proyecto**. En cuanto a [la tarea](https://github.com/IIC2143-2020-1/proyecto/blob/master/tarea_ruby/enunciado_tarea_ruby.pdf), pueden usar **la versión que ustedes prefieran entre `ruby 2.6.x` y `ruby 2.7.0`**. Asegúrense de incluir un `README.md` en su tarea explicitando la versión que usaron (por _default_ usaremos `ruby 2.7.0` para corregir las tareas). Para el momento que vean esto, todas las menciones de `ruby 2.7.0` en las _issues_ estarán cambiadas a `ruby 2.6.x`.

En resúmen:

- **Para la tarea**: _recomendamos_ cualquier versión entre `ruby 2.6.x` y `ruby 2.7.0`.
- **Para el proyecto**: _recomendamos_ la versión `ruby 2.6.x`.

Por suerte, este cambio no debería ser relevante dado que aún no partimos el proyecto. En cualquier caso, disculpen las molestias! :heart:

**Comment by tomasalvarez13** [comment]
Y que versión de rails hay que ocupar?

**Comment by daleal** [comment]
Hola! La versión de `rails` no cambia, por lo que la versión a usar es **`rails 5.2`**.

**Comment by furzuadr** [comment]
Hola! Tengo la 6.0.2.2 de rails, también me sirve o debo bajar a la 5.2?

**Comment by daleal** [comment]
Debes utilizar `rails 5.2`.

**Comment by bgonzlez** [comment]
qué pasará con rails webpacker:install ?? u otros comandos que requieran un rails superior?

**Comment by daleal** [comment]
Los comandos que incluyan `webpacker` no serán necesarios en el desarrollo de su aplicación (en vez de `webpacker`, utilizaremos el famoso [asset pipeline](https://guides.rubyonrails.org/asset_pipeline.html) de rails).

**Comment by camaruri** [comment]
como puedo cambiar la version de rails que estoy usando, tengo usando la 6.0.2 y quiero usar la 5.2 para el proyecto

**Comment by daleal** [comment]
Para instalar `rails 5.2` puedes ejecutar `gem install rails -v '5.2'`. Para inicializar un proyecto nuevo usando `rails 5.2` puedes ejecutar `rails _5.2_ new appname`.
