### ISSUE TITLE
Problemas de Instalación

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2143-2020-1/proyecto#80]
Estoy com muchos problemas de instalacion, traté de muchas formas para lograr ejecutar el server, intente de muchas maneras(primero solo intente instalar lo que pedia, todas las gemas necesarias, ejecutar, ingresar el localhost pero me tirava un error para ingresar, lo resolvi y despues me tiro otro error para conectarme: 'fe_sendauth: no password supplied') así que intente formatear mi notebook y instalar ubuntu con un pendrive, no logré, primero me tiro un error Error Communicating to TPM chip, desative el TPM en la bios y continue teniendo problemas ' 0.777732] integrity: Problem loading X.509 certificate' pase algunas horas buscando posibles soluciones y no logre solucionar.
despues de eso , intente crear una marquina virtual en otro computador, active el Virtualization en la Bios y descargué 2 programas para maquinas virtuales, Oracle VM y Hyper-V, pasa que con Oracle VM me tira errores al instalar Ubuntu,Kubuntu ETC (la instalación crashea y no se puede completar) y con Hyper-V me pide un usuario y password de xorg
En ese otro computador tambien intente instalar la aplicacion y correr el servidor pero me tira más errores ( Webpacker configuration file not found C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:95:in `rescue in load': Webpacker configuration file not found C:/Users/2080 Super/Desktop/Rails_Software/softwareapp/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - C:/Users/2080 Super/Desktop/Rails_Software/softwareapp/config/webpacker.yml (RuntimeError))

**Comment by elramirezv** [comment]
Hola @csantiagopaz ! 

> ... ingresar el localhost pero me tirava un error para ingresar, lo resolvi y despues me tiro otro error para conectarme: 'fe_sendauth: no password supplied')

Esto es un error de configuración del archivo `database.yml`. El servidor no puede conectarse con la base de datos. Hemos colocado varias soluciones a este problema en otras issues 👍 

> ubuntu con un pendrive, no logré, primero me tiro un error Error Communicating to TPM chip, desative el TPM en la bios y continue teniendo problemas ' 0.777732] integrity: Problem loading X.509 certificate' pase algunas horas buscando posibles soluciones y no logre solucionar.
despues de eso , intente crear una marquina virtual en otro computador, active el Virtualization en la Bios y descargué 2 programas para maquinas virtuales, Oracle VM y Hyper-V, pasa que con Oracle VM me tira errores al instalar Ubuntu,Kubuntu ETC (la instalación crashea y no se puede completar) y con Hyper-V me pide un usuario y password de xorg

No somos expertos en particiones ni máquinas virtuales, asique no podemos hacer mucho con errores tan específicos.

>  Webpacker configuration file not found C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:95:in `rescue in load': Webpacker configuration file not found C:/Users/2080 Super/Desktop/Rails_Software/softwareapp/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - C:/Users/2080 Super/Desktop/Rails_Software/softwareapp/config/webpacker.yml (RuntimeError))

`rails 5.2` no necesita webpacker, asique probablemente hayas instalado `rails 6`.

Te recomiendo intentar solucionar el primer problema, ya que solamente es un error de configuración del `database.yml`. Lo otro es que alguno de tus compañeros suba la aplicación al repositorio (con `rails 5.2`y una buena configuración del `database.yml`) y solamente hagas `git clone` 😄

**Comment by daleal** [comment]
Hola! En primer lugar, el error `fe_sendauth: no password supplied` está más que documentado en las issues del curso, incluso hay una pinneada. En segundo lugar, el error de `webpacker` solamente ocurre cuando usas `rails 6`, y nosotros especificamos que utilizaríamos `rails 5.2`, por lo que deberías ser capaz de resolver cualquiera de esos dos problemas utilizando las issues del curso.
