### ISSUE TITLE
NoDatabaseError: FATAL: database "test_app" does not exist

### ISSUE THREAD

**Issue by bgonzlez** [IIC2143-2020-1/proyecto#81]
Hola, cree una base de datos en pgadmin llamada test app, luego corrí rake db:migrate y aparece esto:
![Captura de Pantalla 2020-04-08 a la(s) 21 42 23](https://user-images.githubusercontent.com/53842152/78849232-e2ece580-79e1-11ea-827e-213ad4ae9298.png), ya puse el user: postgres y la clave en blanco, no sé si el problema es de servidores y si tengo que desinstalar todo y hacerlo nuevamente (me dijeron que lo hiciera con homebrew). Gracias!!

**Comment by daleal** [comment]
Hola! Tu aplicación si está conectada a la base de datos, pero no existe una base de datos dentro de Postgres para tu app. Lo que debes hacer es primero ejecutar `rails db:create` y luego ya puedes ejecutar `rails db:migrate`. Saludos!

**Comment by bgonzlez** [comment]
Gracias, pude correrlo pero después voy a pgadmin para actualizar las tablas que creé y no hay nada, qué pudo haber pasado?

**Comment by bgonzlez** [comment]
No funcionó create, tengo el siguiente error :(
![Captura de Pantalla 2020-04-08 a la(s) 22 26 48](https://user-images.githubusercontent.com/53842152/78851595-2a767000-79e8-11ea-987f-55df0c8df9d9.png)

**Comment by valerojasm** [comment]
Hola! Puedes subir un screenshot del archivo `database.yml`? Está en config

**Comment by bgonzlez** [comment]
Holaa, siii aquí está:
![Captura de Pantalla 2020-04-08 a la(s) 22 39 03](https://user-images.githubusercontent.com/53842152/78852254-d40a3100-79e9-11ea-8378-691cedabf715.png)

**Comment by valerojasm** [comment]
Yap, es porque agregaste en algún minuto que la base de datos ocupe sqlite3, mientras que tu adaptador está ocupando postgres. Elimina las líneas 16, 25 y 29, y mueve las líneas 14, 15, 17 y 18 (encoding, database, username y password) a default, debajo de timeout. Corre de nuevo `db:create` y no deberías tener problemas. Si es que persisten, clona el repo de lo que llevan de nuevo (o crea una app nueva si es que no han subido nada aún) y solo agrega tu username y password a default esta vez, y ahí corres create y migrate y etc. Avísame cómo te va!

**Comment by bgonzlez** [comment]
sii, lo intenté con una nueva y ese error se arregló, ahora con migrate aparece esto 😿 
![Captura de Pantalla 2020-04-08 a la(s) 23 04 10](https://user-images.githubusercontent.com/53842152/78853662-6d871200-79ed-11ea-8efa-e5b875ee17d3.png)

**Comment by daleal** [comment]
La buena noticia es que las bases de datos ya se crean y migran correctamente! :tada:
Podrías decirme qué archivos hay en tu carpeta `db/migrate`? En caso de haber múltiples, por favor copia el contenido de cada uno de ellos en un _formatted text_ para saber qué hay dentro.

**Comment by bgonzlez** [comment]
Hola, disculpa busqué, pero a qué te refieres con formatted text?

**Comment by daleal** [comment]
Algo así:

```rb
class CreateCourses < ActiveRecord::Migration[5.1]
  def change
    create_table :courses do |t|
      t.string :initials
      t.string :name
      t.string :teacher_name
      t.timestamps
    end
  end
end
```

**Comment by bgonzlez** [comment]
Ahora si!!

```ruby
class CreateHolas < ActiveRecord::Migration[5.2]
  def change
    create_table :holas do |t|
      t.string :nombre
      t.timestamps
    end
  end
end

**Comment by bgonzlez** [comment]
Creo que no se subieron las 2?:

```ruby
class CreateUsers < ActiveRecord::Migration[5.2]
  def change
    create_table :users do |t|
      t.string :name
      t.string :email_string

      t.timestamps
    end
  end
end

**Comment by daleal** [comment]
Esos son tus únicos archivos dentro de las migraciones? De ser así, trata de ejecutar lo siguiente:

```bash
rails db:drop
rails db:create
rails db:migrate
```

Aprovecha de mandarme también lo que tiene tu `Gemfile` (si lo anterior no te funciona)

**Comment by bgonzlez** [comment]
eso lo debo ejecutar después de poner rails generate model etc? o simplemente lo pongo en la terminal?

**Comment by daleal** [comment]
Lo que hace el comando `rails generate model` es crear dos archivos: un archivo en tu carpeta `app/models` con el modelo (va a ser un archivo casi vacío) y un archivo en `db/migrate` con la migración. Después, para decirle a tu base de datos "voy a usar este modelo" ejecutas `rails db:migrate`, pero tu base de datos dice que ya tiene un modelo `user`, así que la vamos a destruir con `db:drop`, la vamos a generar vacía con `db:create` y después ejecutas las migraciones con `db:migrate`, todo desde el terminal

**Comment by bgonzlez** [comment]
Oka, no tuve ningún error, adjunto ahora gemfile:
![Uploading Captura de Pantalla 2020-04-10 a la(s) 01.09.17.png…]()

**Comment by bgonzlez** [comment]
Oka, no tuve ningún error, adjunto ahora gemfile:
![Captura de Pantalla 2020-04-10 a la(s) 01 09 17](https://user-images.githubusercontent.com/53842152/78964454-36d1fa00-7ac8-11ea-8a13-4e983246f593.png)

**Comment by daleal** [comment]
Si no tuviste ningún error, ya deberías estar! :tada:

**Comment by bgonzlez** [comment]
Intenté todo de nuevo y sigo teniendo el mismo problema  :c 
![Captura de Pantalla 2020-04-10 a la(s) 01 20 07](https://user-images.githubusercontent.com/53842152/78964941-9b418900-7ac9-11ea-974a-c565cbe4f71d.png)

**Comment by daleal** [comment]
Dado que el problema original parece haber sido resuelto, cerraré la issue. En cualquier caso, mañana les hablará su Product Owner @nabenitez para resolver el nuevo problema (parece ser un problema que necesita un poco de tiempo y comunicación directa). Una vez resuelto, comentará en esta misma issue cuál fue la solución.
