### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_sysopen al hacer rails db:create

### ISSUE THREAD

**Issue by gtvargas** [IIC2143-2020-1/proyecto#82]
Hola, al intentar crear la base de datos me aparece el error Errno::ENOENT: No such file or directory @ rb_sysopen. Después de investigar harto sobre esto lo que pude averiguar es que, valga la redundancia, me está faltando un archivo, pero no logro descifrar cuál es. (Este error le pasaba a mucha gente pero eran todos casos muy distintos que resolvían con detalles específicos de lo que le pasaba a cada uno). No sé si tendrá que ver con la instalación de Postgres (que ya agregué al path), con alguna gema u otra cosa.
Dejo una foto del error:
![image](https://user-images.githubusercontent.com/42195631/78851918-0a937c00-79e9-11ea-98da-e261815704e1.png)

Plis ayuda llevo 2 días tratando de resolverlo 😟 
pd: no hemos hecho cambios con mi grupo en niguno de los archivos que menciona el error.

**Comment by valerojasm** [comment]
Hola! 
Todos los integrantes de tu grupo tienen el mismo error o solo te pasa a ti?

**Comment by gtvargas** [comment]
solo me pasa a mi, mis compañeros pudieron crear la bd

**Comment by daleal** [comment]
Hola! Me podrías confirmar que estás usando Windows?

**Comment by gtvargas** [comment]
Sip, Windows 10

**Comment by daleal** [comment]
Intenta instalar NodeJS en tu computador, reiniciarlo e intentar nuevamente.

**Comment by gtvargas** [comment]
Lo hice y me sigue tirando el mismo error 😕

**Comment by daleal** [comment]
Podrías enviar tu `Gemfile`?

**Comment by gtvargas** [comment]
![image](https://user-images.githubusercontent.com/42195631/79060708-45e6b280-7c56-11ea-898c-f9e36fecb8c2.png)
![image](https://user-images.githubusercontent.com/42195631/79060717-6a428f00-7c56-11ea-8929-deacdb731ec9.png)

**Comment by daleal** [comment]
Por qué estás usando la gema `duktape`?

**Comment by gtvargas** [comment]
no la he usado, no me había dado cuenta que la tenía. la saco del gemfile?

**Comment by daleal** [comment]
Sácala de tu `Gemfile`, ejecuta `bundle install` y vuelve a intentar crear la base de datos

**Comment by gtvargas** [comment]
me sigue tirando el mismo error.
No sé si tendrá que ver pero antes de que me apareciera este error me aparecía el de "no password supplied", lo que intenté arreglar añadiendo Postgres al path porque no estaba. Ahí tuve un problema y se cambió todo el path que tenía, por lo que tuve que investigar como volver al path que tenía antes. Cuando lo hice y volví a instalar postgres añadiendolo a mano al path, al igual que rails (ya no estaban en el path cuando lo restauré), me empezó a aparecer este error.
Te adjunto lo que tengo ahora en el path: (he ido añadiendo a mano algunas cosas que he creido tienen que ver con el problema pero la verdad no entiendo muy bien como funciona lo del path):
![image](https://user-images.githubusercontent.com/42195631/79061517-07092a80-7c5f-11ea-9479-c1e75721c95c.png)
Estas son las variables de entorno del sistema.

**Comment by daleal** [comment]
Oof, con toda certeza problema, pero es un error muy oscuro como para que podamos ayudarte en una issue. Lo que probablemente deberías hacer sería hacer una partición e instalar Ubuntu. Cerraré la issue porque el problema fue encontrado pero no podemos ofrecerte una solución.
