### ISSUE TITLE
Cambio de windows a ubuntu

### ISSUE THREAD

**Issue by perezpefaur** [IIC2143-2020-1/proyecto#83]
Hola, ya me baje la máquina virtual para  correr linux con ubuntu pero me surgieron varias dudas:
1) La versión de ruby que recomienda ruby es una distinta de la que corrigen en el proyecto, esto no importa? Me bajo la que corrigen el proyecto o da lo mismo?
2) supongo que la versión de rails efectivamente si tiene que ser la 5.2 sin excepciones (¿?)
3) La versión de postgresql 12 en ubuntu 19, es muy difícil de encontrar y estoy con problemas con la instalación cuando encuentro una pagina que lo explica. Sera necesario tener esta version de postgresql?

**Comment by elramirezv** [comment]
Hola @perezpefaur 😁

- 1 y 2 está en #8 

- 3 está en #22
