### ISSUE TITLE
Duda Rubocop

### ISSUE THREAD

**Issue by Pdesolmi** [IIC2143-2020-1/proyecto#84]
Hola, tengo una duda sobre el uso correcto de rubocop, ya que he buscado en distintas partes y me salen distintas cosas. Una de las formas que vi era crear un archivo llamado ```.rubocop.yml``` dentro del directorio de nuestra app y escribir el siguiente código dentro (que es lo que no estoy seguro de que este bien ya que se excluyen muchos archivos)
```AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - db/**
    - config/**
    - script/**
    - vendor/**/* # Circle adds the rubies here
```
 Luego correr ```rubocop --auto-gen-config``` lo que nos crea un archivo llamado ```rubocop_todo.yml``` con las offensas correspondientes a cada tipo. Cuando corro el comando ```rubocop``` solo, después de hacer todo esto me dice no offenses detected, pero en el archivo ```rubocop_todo.yml```  me dice que hay 8, entonces no estoy muy seguro. Yo creo que estoy mezclando cosas distintas. Sería ideal si alguien me puede aclarar el uso de ```rubocop```.

Muchas gracias

**Comment by daleal** [comment]
Hola! 

En primer lugar, los excludes tienen sentido. Si te fijas, en todas esas carpetas hay código auto-generado, por lo que no tiene sentido lintear archivos en esos directorios (a menos que quieras estilar todos los archivos que se creen).

Con respecto al funcionamiento de la gema, lo que pasa es que `rubocop` es una herramienta compleja y extensible. Cuando creas un `.rubocop_todo.yml`, lo que hace rubocop es analizar tu código, encontrar las ofensas y añadirlas **como excepciones** al `.rubocop_todo.yml`. Luego, puedes heredar de `.rubocop_todo.yml` en tu `.rubocop.yml` (archivo principal). Te recomiendo crear solamente un `.rubocop.yml`, ignorar las carpetas con código auto-generado (como migraciones, por ejemplo) y en ese mismo archivo agregar/ignorar reglas.

Ojalá te haya ayudado! :whale:

**Comment by Pdesolmi** [comment]
Osea hay que revisar los archivos que nosotros creemos o modifiquemos nomas.
Muchas gracias

**Comment by daleal** [comment]
Realmente tienes la libertad de usar el linter como te parezca más conveniente. A mi parecer, lo más lógico es lintear solo lo que uses y no lo que se auto-genere.
