### ISSUE TITLE
Error Rubocop

### ISSUE THREAD

**Issue by benito-tondreaux** [IIC2143-2020-1/proyecto#86]
Hola!! 

Cuando tengo instalado rubocop y con el archivo .rubocop.yml ya modificado, al ejecutar "rubocop" en la consola, me indica el siguiente error:

![IMG-1218](https://user-images.githubusercontent.com/53802150/79027691-30409280-7b5b-11ea-87e6-a383bc695e0f.jpg)

![IMG-1219](https://user-images.githubusercontent.com/53802150/79027699-3767a080-7b5b-11ea-8b25-1693e2e6ccea.jpg)

Estuve buscando el error en internet y encontré que este mensaje en amarillo es sólo una advertencia, sin embargo el error que indica:

incompatible character encodings: UTF-8 and Windows-1252

No permite que rubocop revise los archivos.

De hecho, mi compañero de grupo realizó este proceso de instalación y modificación de rubocop, pero a el sí le funciona rubocop. Yo hice git clone del repositorio, sin cambiar nada ejecuté rubocop y aún así me indica este error.

**Comment by daleal** [comment]
Hola! Efectivamente el primer `log` es solamente una advertencia. El problema comienza en la línea que dice `incompatible character encodings: UTF-8 and Windows-1252`. Dado que el problema es tan particular, lo más probable es que necesites hablarlo con tu product owner para que puedan resolverlo con una comunicación más fluida. De igual manera, podrías por favor enviar el contenido de tu archivo `.rubocop.yml` y de tu `Gemfile`? Por favor envíalos como _formatted text_ y **no** como imágenes.

**Comment by benito-tondreaux** [comment]
Si claro, en el Gemfile tengo:
```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.4', '>= 5.2.4.2'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'rubocop', require: false
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

Y en el .rubocop.yml tengo:
```yml
AllCops:
  Includes:
    - config/routes.rb
    - app/models/*
  Excludes:
    - db/**
    #- config/**/*
    - script/**
    - vendor/**/*
    - tmp/**
    - test/**
    - storage/**/*
    - public/*
    - lib/**
    - bin/**

Metrics/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false
```

**Comment by daleal** [comment]
A simple vista no parece haber nada malo. Te recomiendo pedirle ayuda directamente a tu Product Owner para poder resolver el problema. Una vez resuelto, te agradecería que escribieras en esta misma issue cuál fue el problema. Dado que esto se resolverá por otro medio, cerraré esta issue.

**Comment by gustavo-toro** [comment]
Hola, pudiste solucionarlo? Tengo el mismo problema.

**Comment by benito-tondreaux** [comment]
Hola, sí pude.

Al final el problema era el path, como yo llamé a la carpeta "ingeniería de software" con una tilde en la "i" entonces me incidaba error. Modifiqué el nombre y al final era ese el problema.

**Comment by gustavo-toro** [comment]
Si, eso era. Muchas gracias, te pasaste.
