### ISSUE TITLE
Github de entrega 

### ISSUE THREAD

**Issue by Tito0906** [IIC2143-2020-1/proyecto#87]
Hola! Primero quería aclarar que ya leí la issue 74 sobre los git para la entrega pero sigue sin quedarme claro cómo relacionar el git que nos entregaron con el git que se creó mediante la explicación de la página de heroku. Explico un poco más a continuación:
- La pagina de heroku está subida y parece funcionar. Para hacerla se siguieron todos los pasos de la guía de heroku. Por esta razón, también se creó un repositorio local (no relacionado al github del grupo) usando los comandos git init, etc. 
- Por otro lado, el repositorio del grupo todavía no ha sido creado.  

Mi duda era si basta con hacer :
```
git remote add origin https://github.com/IIC2143-2020-1/grupo.....git
git push -u origin master
```
para copiar el repositorio que se creó mediante la explicación en la página de heroku en el github del grupo e incluir una carpeta dentro con los archivos de la entrega (en la misma carpeta que la aplicación nomas). O si esto está mal y debemos crear el repositorio del grupo vacío y crear una carpeta dentro, en la cual repetir el proceso de la página de heroku. 
Basicamente, no entiendo cómo debe ser la distribución de las carpetas en el repositorio del grupo y su correcta conexión con la aplicación.

**Comment by rafafdz** [comment]
Hola! 
Lo que dices tu esta bien! Si ya tienes en tu computador una carpeta con el código, basta configurarla para que se sincronice con tu repositorio usando `git remote add <repo>` y luego `git push -u origin master`. Recuerda poner en una carpeta el documento de los relatos de usuario y listo.
