### ISSUE TITLE
Duda Tarea 0

### ISSUE THREAD

**Issue by nicoguz** [IIC2143-2020-1/proyecto#9]
Hola!
La tarea debemos hacerla considerando que se pueden hacer cambios a los datos entregados inicialemente? Es decir, es necesario ponerle setters a los atributos de las clases pedidas?? o basta con poner solamente getters?

Gracias de antemano!

**Comment by daleal** [comment]
Hola! Los datos **no** serán manipulados una vez que sean cargados desde los arcivos `.csv`.

**Comment by nicoguz** [comment]
Oka muchas gracias!
