### ISSUE TITLE
Duda Git - Heroku

### ISSUE THREAD

**Issue by SergioGazali** [IIC2143-2020-1/proyecto#91]
Hola!
Estoy recibiendo el siguiente mensaje en consola al tratar subir mi código al repositorio, en el que pretendía tener un readme y la carpeta con la aplicación, la cual ya está deployada en heroku (creo que por esto entrega un aviso al hacer git add). ¿Qué debería estar haciendo?:
<img width="571" alt="Captura de Pantalla 2020-04-13 a la(s) 16 03 42" src="https://user-images.githubusercontent.com/42220325/79156116-5014c800-7da0-11ea-8067-3adb4a9e0624.png">

Muchas Gracias!

**Comment by elramirezv** [comment]
Hola @SergioGazali !

Lo que está pasando es que dentro de `dccitas_app` hay otro repositorio creado (puedes verlo ejecutando `ls -a` dentro del proyecto, ahí veras una carpeta llamada `.git`), esto pasa porque Rails crea uno por defecto. Lo que tienes que hacer es "linkear" el que crea Rails con el remoto de tu grupo. 

En este [link](https://help.github.com/en/github/importing-your-projects-to-github/adding-an-existing-project-to-github-using-the-command-line) aparece lo que tienes que hacer. En tu caso, tendrías que empezar desde el paso 5 😄 

**EDIT:** Con respecto a lo de Heroku, una vez hecho lo que te dije, dentro de `dcc_citas` podrás hacer el deploy 👍 (tienes que estar parado adentro de `dcc_citas`)
