### ISSUE TITLE
Error occurred while installing pg

### ISSUE THREAD

**Issue by figarcia3** [IIC2143-2020-1/proyecto#94]
Hola! he tenido este error hace mucho tiempo y no he podido solucionarlo. Al correr bundle install aparece este error al leer el gemfile.
![Captura de pantalla de 2020-04-20 21-52-00](https://user-images.githubusercontent.com/48328327/79816425-37348580-8351-11ea-9438-a675ccf30f1c.png)
Corro el comando que me indica en el final y tambien genera un error 
![Captura de pantalla de 2020-04-20 21-55-23](https://user-images.githubusercontent.com/48328327/79816619-a90ccf00-8351-11ea-8693-c3cb1c19ecfe.png)

**Comment by meretamal** [comment]
Hola 😁 !!

Es probable que te falten las dependencias de desarrollador.

¿Podrías intentar correr `sudo apt-get install libpq-dev` y después volver a correr `bundle install`?

**Comment by figarcia3** [comment]
Eso era! Gracias!
