### ISSUE TITLE
Duda database heroku

### ISSUE THREAD

**Issue by rodobkn** [IIC2143-2020-1/proyecto#95]
Hola!

Estaba creando un poryecto con rails de forma solitaria, para practicar. Todo bien con mi deploy en heroku, hasta que las tuplas que había insertado en mi database, no estaban en el deploy hecho en heroku.

Me explico, por ejemplo yo cree una tabla llamada "futbolistas" con dos atributos:
-nombre: string
-dorsal: int

Y imaginemos que en el index me aparece los futbolistas con su nombre y dorsal respectivo. Desde mi computador(localhost) me salía:

Bienvenido a mi pagina de futbolistas!
Ronaldinho 10
Zidane 4

Pero en Heroku me salía:

Bienvenido a mi pagina de futbolistas!

Hice las migraciones correspondientes, es más, hasta desde heroku podemos crear nuevos futbolistas, pero no me salen los mismos que yo tenía trabajando localmente.

Entonces quería saber por que pasa esto, y donde podría ver las tuplas de mis tablas, ya que en pgadmin4 salen las que yo tenía de formal local (ronaldinho 10, Zidane 4).

Gracias!

**Comment by elramirezv** [comment]
Hola @rodobkn !

Nose si te entendí bien, pero tu pregunta es: ¿Por qué no te aparece la misma información de localhost en Heroku? 

Si es así, la respuesta es porque la información de localhost es solo local, la data que hay en `Postgres` de tu computador y la base de datos de Heroku es diferente (lo que se ve en Heroku es lo que pueden ver todas las personas que ocupan tu aplicación). Es por eso qu existen las migraciones, van representando los cambios "estructurales" que se hacen a la base de datos y así ambas se puedan  mantener "sincronizadas" (pero solo en la forma).

Para poder ver lo que hay en la base de datos de Heroku, puedes correr la consola de Rails con: `heroku run rails c` y luego hacer consultas como: `Modelo.all`

Espero que haya quedado un poco más claro 😁
