### ISSUE TITLE
Problema devise

### ISSUE THREAD

**Issue by jalliende** [IIC2143-2020-1/proyecto#97]
Hola, seguí los pasos de la ayudantia pero no me reconoce las rutas. A que se puede deber? busque vídeos en internet pero no explican mucho, ya que son parecidos a lo de la ayudantia.
mi archivo de routes se ve asi:
![image](https://user-images.githubusercontent.com/48294819/79911081-c68f7680-83ed-11ea-92b8-7938aa67cc76.png)
y el error en el browser asi:
![image](https://user-images.githubusercontent.com/48294819/79911208-fe96b980-83ed-11ea-9cb5-a2e793f44b29.png)
Muchas gracias

**Comment by elramirezv** [comment]
Hola @jalliende !

Probaste con `sign_up` en vez de `sing_up` ?

**Comment by jalliende** [comment]
sing_in en vez de sing_up? por que si esa era la pregunta si probe jaja

**Comment by valerojasm** [comment]
Hola @jalliende !

Te lo está diciendo porque está mal escrito. Es **sign**, ese debe ser el problema.

**Comment by jalliende** [comment]
que estupido jajaja voy a probar

**Comment by jalliende** [comment]
Borre todo el progreso desde la entrega 0 la app y trate de nuevo ahora con sign y no funciono

**Comment by elramirezv** [comment]
@jalliende Pero no creo que sea el mismo error, qué te tira ahora ?

**Comment by jalliende** [comment]
Ahí me funciono, pero no entendí por que creamos las views y los controllers en la ayudantia. Si podia acceder a /users/sign_up sin la creacion de estos.
