### ISSUE TITLE
Diagrama identidad relación

### ISSUE THREAD

**Issue by ChayoPerez** [IIC2143-2020-1/proyecto#98]
Hola!
Tengo una duda. En BDD los atributos de las cosas se ponían en círculos, pero nuestro diagrama tiene muchos atributos para que se vea práctico/legible al llenarlo de elipses. ¿Puedo dejar los atributos en tablas? Conservando las líneas, flechas y relaciones, obvio.

Gracias!

**Comment by daleal** [comment]
Hola! Si, pueden hacerlo.
